//
//  ExampleTests.swift
//  ExampleTests
//
//  Created by Aurelien on 19/05/2019.
//  Copyright © 2019 chronotruck. All rights reserved.
//

import XCTest
@testable import FlagPhoneNumber

class ExampleTests: XCTestCase {

	let textfield = FPNTextField()

	override func setUp() {
		super.setUp()
		//		Put setup code here. This method is called before the invocation of each test method in the class.
	}

	override func tearDown() {
		//		Put teardown code here. This method is called after the invocation of each test method in the class.
		super.tearDown()
	}

	func testSetFlagAndPhoneNumber() {
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "FR")!)
		textfield.set(phoneNumber: "0600000000")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+33")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FR")
		XCTAssertEqual(textfield.text, "6 00 00 00 00")
	}

	func testSetPhoneNumber() {
		textfield.set(phoneNumber: "+93234567890")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+93")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AF")
		XCTAssertEqual(textfield.text, "23 456 7890")
		textfield.set(phoneNumber: "+27101234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+27")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ZA")
		XCTAssertEqual(textfield.text, "10 123 4567")
		textfield.set(phoneNumber: "+35522345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+355")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AL")
		XCTAssertEqual(textfield.text, "22 345 678")
		textfield.set(phoneNumber: "+21312345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+213")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DZ")
		XCTAssertEqual(textfield.text, "12 34 56 78")
		textfield.set(phoneNumber: "+4930123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+49")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DE")
		XCTAssertEqual(textfield.text, "30 123456")
		textfield.set(phoneNumber: "+376712345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+376")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AD")
		XCTAssertEqual(textfield.text, "712 345")
		textfield.set(phoneNumber: "+244222123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+244")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AO")
		XCTAssertEqual(textfield.text, "222 123 456")
		textfield.set(phoneNumber: "+12644612345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AI")
		XCTAssertEqual(textfield.text, "264-461-2345")
		textfield.set(phoneNumber: "+12684601234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AG")
		XCTAssertEqual(textfield.text, "268-460-1234")
		textfield.set(phoneNumber: "+966112345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+966")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SA")
		XCTAssertEqual(textfield.text, "11 234 5678")
		textfield.set(phoneNumber: "+541123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+54")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AR")
		XCTAssertEqual(textfield.text, "11 2345-6789")
		textfield.set(phoneNumber: "+37410123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+374")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AM")
		XCTAssertEqual(textfield.text, "10 123456")
		textfield.set(phoneNumber: "+2975212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+297")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AW")
		XCTAssertEqual(textfield.text, "521 2345")
		textfield.set(phoneNumber: "+61212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+61")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AU")
		XCTAssertEqual(textfield.text, "2 1234 5678")
		textfield.set(phoneNumber: "+431234567890")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+43")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AT")
		XCTAssertEqual(textfield.text, "1 234567890")
		textfield.set(phoneNumber: "+994123123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+994")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AZ")
		XCTAssertEqual(textfield.text, "12 312 34 56")
		textfield.set(phoneNumber: "+12423456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BS")
		XCTAssertEqual(textfield.text, "242-345-6789")
		textfield.set(phoneNumber: "+97317001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+973")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BH")
		XCTAssertEqual(textfield.text, "1700 1234")
		textfield.set(phoneNumber: "+88027111234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+880")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BD")
		XCTAssertEqual(textfield.text, "2-7111234")
		textfield.set(phoneNumber: "+12464123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BB")
		XCTAssertEqual(textfield.text, "246-412-3456")
		textfield.set(phoneNumber: "+3212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+32")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BE")
		XCTAssertEqual(textfield.text, "12 34 56 78")
		textfield.set(phoneNumber: "+5012221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+501")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BZ")
		XCTAssertEqual(textfield.text, "222-1234")
		textfield.set(phoneNumber: "+14412345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BM")
		XCTAssertEqual(textfield.text, "441-234-5678")
		textfield.set(phoneNumber: "+22920211234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+229")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BJ")
		XCTAssertEqual(textfield.text, "20 21 12 34")
		textfield.set(phoneNumber: "+9752345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+975")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BT")
		XCTAssertEqual(textfield.text, "2 345 678")
		textfield.set(phoneNumber: "+375152450911")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+375")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BY")
		XCTAssertEqual(textfield.text, "152 45-09-11")
		textfield.set(phoneNumber: "+59122123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+591")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BO")
		XCTAssertEqual(textfield.text, "2 2123456")
		textfield.set(phoneNumber: "+38730212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+387")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BA")
		XCTAssertEqual(textfield.text, "30 212-345")
		textfield.set(phoneNumber: "+2672401234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+267")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BW")
		XCTAssertEqual(textfield.text, "240 1234")
		textfield.set(phoneNumber: "+551123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+55")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BR")
		XCTAssertEqual(textfield.text, "11 2345-6789")
		textfield.set(phoneNumber: "+6732345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+673")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BN")
		XCTAssertEqual(textfield.text, "234 5678")
		textfield.set(phoneNumber: "+3592123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+359")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BG")
		XCTAssertEqual(textfield.text, "2 123 456")
		textfield.set(phoneNumber: "+22620491234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+226")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BF")
		XCTAssertEqual(textfield.text, "20 49 12 34")
		textfield.set(phoneNumber: "+25722201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+257")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BI")
		XCTAssertEqual(textfield.text, "22 20 12 34")
		textfield.set(phoneNumber: "+85523756789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+855")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KH")
		XCTAssertEqual(textfield.text, "23 756 789")
		textfield.set(phoneNumber: "+237222123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+237")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CM")
		XCTAssertEqual(textfield.text, "2 22 12 34 56")
		textfield.set(phoneNumber: "+12042345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CA")
		XCTAssertEqual(textfield.text, "204-234-5678")
		textfield.set(phoneNumber: "+2382211234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+238")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CV")
		XCTAssertEqual(textfield.text, "221 12 34")
		textfield.set(phoneNumber: "+56221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+56")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CL")
		XCTAssertEqual(textfield.text, "2 2123 4567")
		textfield.set(phoneNumber: "+861012345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+86")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CN")
		XCTAssertEqual(textfield.text, "10 1234 5678")
		textfield.set(phoneNumber: "+35722345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+357")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CY")
		XCTAssertEqual(textfield.text, "22 345678")
		textfield.set(phoneNumber: "+5712345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+57")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CO")
		XCTAssertEqual(textfield.text, "1 2345678")
		textfield.set(phoneNumber: "+2697712345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+269")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KM")
		XCTAssertEqual(textfield.text, "771 23 45")
		textfield.set(phoneNumber: "+242222123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+242")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CG")
		XCTAssertEqual(textfield.text, "22 212 3456")
		textfield.set(phoneNumber: "+2431234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+243")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CD")
		XCTAssertEqual(textfield.text, "12 34567")
		textfield.set(phoneNumber: "+85021234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+850")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KP")
		XCTAssertEqual(textfield.text, "2 123 4567")
		textfield.set(phoneNumber: "+8222123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+82")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KR")
		XCTAssertEqual(textfield.text, "2-212-3456")
		textfield.set(phoneNumber: "+50622123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+506")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CR")
		XCTAssertEqual(textfield.text, "2212 3456")
		textfield.set(phoneNumber: "+22521234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+225")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CI")
		XCTAssertEqual(textfield.text, "21 23 45 67")
		textfield.set(phoneNumber: "+38512345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+385")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HR")
		XCTAssertEqual(textfield.text, "1 2345 678")
		textfield.set(phoneNumber: "+5371234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+53")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CU")
		XCTAssertEqual(textfield.text, "7 1234567")
		textfield.set(phoneNumber: "+4532123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+45")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DK")
		XCTAssertEqual(textfield.text, "32 12 34 56")
		textfield.set(phoneNumber: "+25321360003")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+253")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DJ")
		XCTAssertEqual(textfield.text, "21 36 00 03")
		textfield.set(phoneNumber: "+17674201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DM")
		XCTAssertEqual(textfield.text, "767-420-1234")
		textfield.set(phoneNumber: "+50321234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+503")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SV")
		XCTAssertEqual(textfield.text, "2123 4567")
		textfield.set(phoneNumber: "+34810123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+34")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ES")
		XCTAssertEqual(textfield.text, "810 12 34 56")
		textfield.set(phoneNumber: "+3723212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+372")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "EE")
		XCTAssertEqual(textfield.text, "321 2345")
		textfield.set(phoneNumber: "+20234567890")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+20")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "EG")
		XCTAssertEqual(textfield.text, "2 34567890")
		textfield.set(phoneNumber: "+97122345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+971")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AE")
		XCTAssertEqual(textfield.text, "2 234 5678")
		textfield.set(phoneNumber: "+59322123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+593")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "EC")
		XCTAssertEqual(textfield.text, "2-212-3456")
		textfield.set(phoneNumber: "+2918370362")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+291")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ER")
		XCTAssertEqual(textfield.text, "8 370 362")
		//		textfield.set(phoneNumber: "+39669812345")
		//		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+39")
		//		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VA")
		//		XCTAssertEqual(textfield.text, "6 6981 2345")
		textfield.set(phoneNumber: "+6913201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+691")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FM")
		XCTAssertEqual(textfield.text, "320 1234")
		textfield.set(phoneNumber: "+12015550123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "US")
		XCTAssertEqual(textfield.text, "201-555-0123")
		textfield.set(phoneNumber: "+251111112345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+251")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ET")
		XCTAssertEqual(textfield.text, "11 111 2345")
		textfield.set(phoneNumber: "+6793212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+679")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FJ")
		XCTAssertEqual(textfield.text, "321 2345")
		textfield.set(phoneNumber: "+358131234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+358")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FI")
		XCTAssertEqual(textfield.text, "13 1234567")
		textfield.set(phoneNumber: "+33123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+33")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FR")
		XCTAssertEqual(textfield.text, "1 23 45 67 89")
		textfield.set(phoneNumber: "+2414422222")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+241")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GA")
		XCTAssertEqual(textfield.text, "4 42 22 22")
		textfield.set(phoneNumber: "+2205661234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+220")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GM")
		XCTAssertEqual(textfield.text, "566 1234")
		textfield.set(phoneNumber: "+995322123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+995")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GE")
		XCTAssertEqual(textfield.text, "322 12 34 56")
		textfield.set(phoneNumber: "+233302345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+233")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GH")
		XCTAssertEqual(textfield.text, "30 234 5678")
		textfield.set(phoneNumber: "+35020012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+350")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GI")
		XCTAssertEqual(textfield.text, "200 12345")
		textfield.set(phoneNumber: "+14732691234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GD")
		XCTAssertEqual(textfield.text, "473-269-1234")
		textfield.set(phoneNumber: "+302123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+30")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GR")
		XCTAssertEqual(textfield.text, "21 2345 6789")
		textfield.set(phoneNumber: "+299321000")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+299")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GL")
		XCTAssertEqual(textfield.text, "32 10 00")
		textfield.set(phoneNumber: "+590590201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+590")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GP")
		XCTAssertEqual(textfield.text, "590 20 12 34")
		textfield.set(phoneNumber: "+16713001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GU")
		XCTAssertEqual(textfield.text, "671-300-1234")
		textfield.set(phoneNumber: "+50222456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+502")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GT")
		XCTAssertEqual(textfield.text, "2245 6789")
		textfield.set(phoneNumber: "+441481256789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+44")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GG")
		XCTAssertEqual(textfield.text, "1481 256789")
		textfield.set(phoneNumber: "+22430241234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+224")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GN")
		XCTAssertEqual(textfield.text, "30 24 12 34")
		textfield.set(phoneNumber: "+240333091234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+240")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GQ")
		XCTAssertEqual(textfield.text, "333 091 234")
		textfield.set(phoneNumber: "+245443201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+245")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GW")
		XCTAssertEqual(textfield.text, "443 201 234")
		textfield.set(phoneNumber: "+5922201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+592")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GY")
		XCTAssertEqual(textfield.text, "220 1234")
		textfield.set(phoneNumber: "+594594101234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+594")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GF")
		XCTAssertEqual(textfield.text, "594 10 12 34")
		textfield.set(phoneNumber: "+50922453300")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+509")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HT")
		XCTAssertEqual(textfield.text, "22 45 3300")
		textfield.set(phoneNumber: "+50422123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+504")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HN")
		XCTAssertEqual(textfield.text, "2212-3456")
		textfield.set(phoneNumber: "+85221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+852")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HK")
		XCTAssertEqual(textfield.text, "2123 4567")
		textfield.set(phoneNumber: "+3612345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+36")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HU")
		XCTAssertEqual(textfield.text, "1 234 5678")
		textfield.set(phoneNumber: "+911123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+91")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IN")
		XCTAssertEqual(textfield.text, "11 2345 6789")
		textfield.set(phoneNumber: "+62612345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+62")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ID")
		XCTAssertEqual(textfield.text, "61 2345678")
		textfield.set(phoneNumber: "+96412345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+964")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IQ")
		XCTAssertEqual(textfield.text, "1 234 5678")
		textfield.set(phoneNumber: "+982123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+98")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IR")
		XCTAssertEqual(textfield.text, "21 2345 6789")
		textfield.set(phoneNumber: "+3532212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+353")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IE")
		XCTAssertEqual(textfield.text, "22 12345")
		textfield.set(phoneNumber: "+3544101234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+354")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IS")
		XCTAssertEqual(textfield.text, "410 1234")
		textfield.set(phoneNumber: "+97221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+972")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IL")
		XCTAssertEqual(textfield.text, "2-123-4567")
		textfield.set(phoneNumber: "+39054988")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+39")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IT")
		XCTAssertEqual(textfield.text, "54 988")
		textfield.set(phoneNumber: "+61891641234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+61")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CX")
		XCTAssertEqual(textfield.text, "8 9164 1234")
		textfield.set(phoneNumber: "+672106609")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+672")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NF")
		XCTAssertEqual(textfield.text, "10 6609")
		textfield.set(phoneNumber: "+441624756789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+44")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IM")
		XCTAssertEqual(textfield.text, "1624 756789")
		textfield.set(phoneNumber: "+358181234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+358")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AX")
		XCTAssertEqual(textfield.text, "18 1234567")
		textfield.set(phoneNumber: "+13452221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KY")
		XCTAssertEqual(textfield.text, "345-222-1234")
		textfield.set(phoneNumber: "+61891621234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+61")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CC")
		XCTAssertEqual(textfield.text, "8 9162 1234")
		textfield.set(phoneNumber: "+68221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+682")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CK")
		XCTAssertEqual(textfield.text, "21 234")
		textfield.set(phoneNumber: "+298201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+298")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FO")
		XCTAssertEqual(textfield.text, "201234")
		textfield.set(phoneNumber: "+50031234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+500")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FK")
		XCTAssertEqual(textfield.text, "31234")
		textfield.set(phoneNumber: "+16702345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MP")
		XCTAssertEqual(textfield.text, "670-234-5678")
		textfield.set(phoneNumber: "+6922471234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+692")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MH")
		XCTAssertEqual(textfield.text, "247-1234")
		textfield.set(phoneNumber: "+67740123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+677")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SB")
		XCTAssertEqual(textfield.text, "40123")
		textfield.set(phoneNumber: "+16497121234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TC")
		XCTAssertEqual(textfield.text, "649-712-1234")
		textfield.set(phoneNumber: "+12842291234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VG")
		XCTAssertEqual(textfield.text, "284-229-1234")
		textfield.set(phoneNumber: "+13406421234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VI")
		XCTAssertEqual(textfield.text, "340-642-1234")
		textfield.set(phoneNumber: "+18765123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "JM")
		XCTAssertEqual(textfield.text, "876-512-3456")
		textfield.set(phoneNumber: "+81312345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+81")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "JP")
		XCTAssertEqual(textfield.text, "3-1234-5678")
		textfield.set(phoneNumber: "+441534456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+44")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "JE")
		XCTAssertEqual(textfield.text, "1534 456789")
		textfield.set(phoneNumber: "+96262001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+962")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "JO")
		XCTAssertEqual(textfield.text, "6 200 1234")
		textfield.set(phoneNumber: "+77123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+7")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KZ")
		XCTAssertEqual(textfield.text, "712 345 6789")
		textfield.set(phoneNumber: "+254202012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+254")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KE")
		XCTAssertEqual(textfield.text, "20 2012345")
		textfield.set(phoneNumber: "+996312123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+996")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KG")
		XCTAssertEqual(textfield.text, "312 123 456")
		textfield.set(phoneNumber: "+68631234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+686")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KI")
		XCTAssertEqual(textfield.text, "31234")
		textfield.set(phoneNumber: "+96522345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+965")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KW")
		XCTAssertEqual(textfield.text, "2234 5678")
		textfield.set(phoneNumber: "+262262161234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+262")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RE")
		XCTAssertEqual(textfield.text, "262 16 12 34")
		textfield.set(phoneNumber: "+85621212862")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+856")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LA")
		XCTAssertEqual(textfield.text, "21 212 862")
		textfield.set(phoneNumber: "+26622123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+266")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LS")
		XCTAssertEqual(textfield.text, "2212 3456")
		textfield.set(phoneNumber: "+37163123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+371")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LV")
		XCTAssertEqual(textfield.text, "63 123 456")
		textfield.set(phoneNumber: "+9611123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+961")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LB")
		XCTAssertEqual(textfield.text, "1 123 456")
		textfield.set(phoneNumber: "+23121234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+231")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LR")
		XCTAssertEqual(textfield.text, "21 234 567")
		textfield.set(phoneNumber: "+218212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+218")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LY")
		XCTAssertEqual(textfield.text, "21-2345678")
		textfield.set(phoneNumber: "+4232345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+423")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LI")
		XCTAssertEqual(textfield.text, "234 56 78")
		textfield.set(phoneNumber: "+37031234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+370")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LT")
		XCTAssertEqual(textfield.text, "312 34567")
		textfield.set(phoneNumber: "+35227123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+352")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LU")
		XCTAssertEqual(textfield.text, "27 12 34 56")
		textfield.set(phoneNumber: "+85328212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+853")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MO")
		XCTAssertEqual(textfield.text, "2821 2345")
		textfield.set(phoneNumber: "+38922212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+389")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MK")
		XCTAssertEqual(textfield.text, "2 221 2345")
		textfield.set(phoneNumber: "+261202123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+261")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MG")
		XCTAssertEqual(textfield.text, "20 21 234 56")
		textfield.set(phoneNumber: "+60323856789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+60")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MY")
		XCTAssertEqual(textfield.text, "3-2385 6789")
		textfield.set(phoneNumber: "+2651234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+265")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MW")
		XCTAssertEqual(textfield.text, "1 234 567")
		textfield.set(phoneNumber: "+9606701234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+960")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MV")
		XCTAssertEqual(textfield.text, "670-1234")
		textfield.set(phoneNumber: "+22320212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+223")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ML")
		XCTAssertEqual(textfield.text, "20 21 23 45")
		textfield.set(phoneNumber: "+35621001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+356")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MT")
		XCTAssertEqual(textfield.text, "2100 1234")
		textfield.set(phoneNumber: "+212520123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+212")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MA")
		XCTAssertEqual(textfield.text, "520-123456")
		textfield.set(phoneNumber: "+596596301234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+596")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MQ")
		XCTAssertEqual(textfield.text, "596 30 12 34")
		textfield.set(phoneNumber: "+2302012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+230")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MU")
		XCTAssertEqual(textfield.text, "201 2345")
		textfield.set(phoneNumber: "+22235123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+222")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MR")
		XCTAssertEqual(textfield.text, "35 12 34 56")
		textfield.set(phoneNumber: "+262269601234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+262")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "YT")
		XCTAssertEqual(textfield.text, "269 60 12 34")
		textfield.set(phoneNumber: "+522221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+52")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MX")
		XCTAssertEqual(textfield.text, "222 123 4567")
		textfield.set(phoneNumber: "+37322212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+373")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MD")
		XCTAssertEqual(textfield.text, "22 212 345")
		textfield.set(phoneNumber: "+37799123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+377")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MC")
		XCTAssertEqual(textfield.text, "99 12 34 56")
		textfield.set(phoneNumber: "+97650123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+976")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MN")
		XCTAssertEqual(textfield.text, "5012 3456")
		textfield.set(phoneNumber: "+38230234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+382")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ME")
		XCTAssertEqual(textfield.text, "30 234 567")
		textfield.set(phoneNumber: "+16644912345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MS")
		XCTAssertEqual(textfield.text, "664-491-2345")
		textfield.set(phoneNumber: "+25821123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+258")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MZ")
		XCTAssertEqual(textfield.text, "21 123 456")
		textfield.set(phoneNumber: "+951234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+95")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MM")
		XCTAssertEqual(textfield.text, "1 234 567")
		textfield.set(phoneNumber: "+26461221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+264")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NA")
		XCTAssertEqual(textfield.text, "61 221 234")
		textfield.set(phoneNumber: "+6744441234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+674")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NR")
		XCTAssertEqual(textfield.text, "444 1234")
		textfield.set(phoneNumber: "+97714567890")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+977")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NP")
		XCTAssertEqual(textfield.text, "1-4567890")
		textfield.set(phoneNumber: "+50521234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+505")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NI")
		XCTAssertEqual(textfield.text, "2123 4567")
		textfield.set(phoneNumber: "+22720201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+227")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NE")
		XCTAssertEqual(textfield.text, "20 20 12 34")
		textfield.set(phoneNumber: "+23412345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+234")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NG")
		XCTAssertEqual(textfield.text, "1 234 5678")
		textfield.set(phoneNumber: "+6834002")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+683")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NU")
		XCTAssertEqual(textfield.text, "4002")
		textfield.set(phoneNumber: "+4721234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+47")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NO")
		XCTAssertEqual(textfield.text, "21 23 45 67")
		textfield.set(phoneNumber: "+687201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+687")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NC")
		XCTAssertEqual(textfield.text, "20.12.34")
		textfield.set(phoneNumber: "+6432345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+64")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NZ")
		XCTAssertEqual(textfield.text, "3-234 5678")
		textfield.set(phoneNumber: "+96823123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+968")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "OM")
		XCTAssertEqual(textfield.text, "23 123456")
		textfield.set(phoneNumber: "+256312345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+256")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "UG")
		XCTAssertEqual(textfield.text, "31 2345678")
		textfield.set(phoneNumber: "+998662345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+998")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "UZ")
		XCTAssertEqual(textfield.text, "66 234 56 78")
		textfield.set(phoneNumber: "+922123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+92")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PK")
		XCTAssertEqual(textfield.text, "21 23456789")
		textfield.set(phoneNumber: "+6802771234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+680")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PW")
		XCTAssertEqual(textfield.text, "277 1234")
		textfield.set(phoneNumber: "+5072001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+507")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PA")
		XCTAssertEqual(textfield.text, "200-1234")
		textfield.set(phoneNumber: "+6753123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+675")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PG")
		XCTAssertEqual(textfield.text, "312 3456")
		textfield.set(phoneNumber: "+595212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+595")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PY")
		XCTAssertEqual(textfield.text, "21 234 5678")
		textfield.set(phoneNumber: "+31101234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+31")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NL")
		XCTAssertEqual(textfield.text, "10 123 4567")
		textfield.set(phoneNumber: "+5111234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+51")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PE")
		XCTAssertEqual(textfield.text, "1 1234567")
		textfield.set(phoneNumber: "+6321234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+63")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PH")
		XCTAssertEqual(textfield.text, "2 123 4567")
		textfield.set(phoneNumber: "+48123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+48")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PL")
		XCTAssertEqual(textfield.text, "12 345 67 89")
		textfield.set(phoneNumber: "+68940412345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+689")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PF")
		XCTAssertEqual(textfield.text, "40 41 23 45")
		textfield.set(phoneNumber: "+17872345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PR")
		XCTAssertEqual(textfield.text, "787-234-5678")
		textfield.set(phoneNumber: "+351212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+351")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PT")
		XCTAssertEqual(textfield.text, "21 234 5678")
		textfield.set(phoneNumber: "+97444123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+974")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "QA")
		XCTAssertEqual(textfield.text, "4412 3456")
		textfield.set(phoneNumber: "+23621612345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+236")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CF")
		XCTAssertEqual(textfield.text, "21 61 23 45")
		textfield.set(phoneNumber: "+18092345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DO")
		XCTAssertEqual(textfield.text, "809-234-5678")
		textfield.set(phoneNumber: "+40211234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+40")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RO")
		XCTAssertEqual(textfield.text, "21 123 4567")
		textfield.set(phoneNumber: "+441212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+44")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GB")
		XCTAssertEqual(textfield.text, "121 234 5678")
		textfield.set(phoneNumber: "+73011234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+7")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RU")
		XCTAssertEqual(textfield.text, "301 123-45-67")
		textfield.set(phoneNumber: "+250250123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+250")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RW")
		XCTAssertEqual(textfield.text, "250 123 456")
		textfield.set(phoneNumber: "+590590271234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+590")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BL")
		XCTAssertEqual(textfield.text, "590 27 12 34")
		textfield.set(phoneNumber: "+18692361234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KN")
		XCTAssertEqual(textfield.text, "869-236-1234")
		textfield.set(phoneNumber: "+3780549876811")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+378")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SM")
		XCTAssertEqual(textfield.text, "549876811")
		//		textfield.set(phoneNumber: "+590590271234")
		//		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+590")
		//		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MF")
		//		XCTAssertEqual(textfield.text, "590 27-1234")
		textfield.set(phoneNumber: "+508411234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+508")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PM")
		XCTAssertEqual(textfield.text, "41 12 34")
		textfield.set(phoneNumber: "+17842661234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VC")
		XCTAssertEqual(textfield.text, "784-266-1234")
		textfield.set(phoneNumber: "+29022158")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+290")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SH")
		XCTAssertEqual(textfield.text, "22158")
		textfield.set(phoneNumber: "+17584305678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LC")
		XCTAssertEqual(textfield.text, "758-430-5678")
		textfield.set(phoneNumber: "+68522123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+685")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "WS")
		XCTAssertEqual(textfield.text, "22123")
		textfield.set(phoneNumber: "+16846221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AS")
		XCTAssertEqual(textfield.text, "684-622-1234")
		textfield.set(phoneNumber: "+2392221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+239")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ST")
		XCTAssertEqual(textfield.text, "222 1234")
		textfield.set(phoneNumber: "+38110234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+381")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RS")
		XCTAssertEqual(textfield.text, "10 234567")
		textfield.set(phoneNumber: "+2484217123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+248")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SC")
		XCTAssertEqual(textfield.text, "4 217 123")
		textfield.set(phoneNumber: "+221301012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+221")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SN")
		XCTAssertEqual(textfield.text, "30 101 23 45")
		textfield.set(phoneNumber: "+23222221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+232")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SL")
		XCTAssertEqual(textfield.text, "22 221234")
		textfield.set(phoneNumber: "+6561234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+65")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SG")
		XCTAssertEqual(textfield.text, "6123 4567")
		textfield.set(phoneNumber: "+421221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+421")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SK")
		XCTAssertEqual(textfield.text, "2/212 345 67")
		textfield.set(phoneNumber: "+38611234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+386")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SI")
		XCTAssertEqual(textfield.text, "1 123 45 67")
		textfield.set(phoneNumber: "+2524012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+252")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SO")
		XCTAssertEqual(textfield.text, "4 012345")
		textfield.set(phoneNumber: "+249121231234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+249")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SD")
		XCTAssertEqual(textfield.text, "12 123 1234")
		textfield.set(phoneNumber: "+211181234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+211")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SS")
		XCTAssertEqual(textfield.text, "181 234 567")
		textfield.set(phoneNumber: "+94112345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+94")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LK")
		XCTAssertEqual(textfield.text, "112 345 678")
		textfield.set(phoneNumber: "+468123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+46")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SE")
		XCTAssertEqual(textfield.text, "8 12 34 56")
		textfield.set(phoneNumber: "+41212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+41")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CH")
		XCTAssertEqual(textfield.text, "21 234 56 78")
		textfield.set(phoneNumber: "+597211234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+597")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SR")
		XCTAssertEqual(textfield.text, "211-234")
		textfield.set(phoneNumber: "+4779123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+47")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SJ")
		XCTAssertEqual(textfield.text, "79 12 34 56")
		textfield.set(phoneNumber: "+26822171234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+268")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SZ")
		XCTAssertEqual(textfield.text, "2217 1234")
		textfield.set(phoneNumber: "+963112345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+963")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SY")
		XCTAssertEqual(textfield.text, "11 234 5678")
		textfield.set(phoneNumber: "+992372123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+992")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TJ")
		XCTAssertEqual(textfield.text, "372 12 3456")
		textfield.set(phoneNumber: "+886221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+886")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TW")
		XCTAssertEqual(textfield.text, "2 2123 4567")
		textfield.set(phoneNumber: "+255222345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+255")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TZ")
		XCTAssertEqual(textfield.text, "22 234 5678")
		textfield.set(phoneNumber: "+23522501234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+235")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TD")
		XCTAssertEqual(textfield.text, "22 50 12 34")
		textfield.set(phoneNumber: "+420212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+420")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CZ")
		XCTAssertEqual(textfield.text, "212 345 678")
		textfield.set(phoneNumber: "+2463709100")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+246")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IO")
		XCTAssertEqual(textfield.text, "370 9100")
		textfield.set(phoneNumber: "+97022234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+970")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PS")
		XCTAssertEqual(textfield.text, "2 223 4567")
		textfield.set(phoneNumber: "+6621234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+66")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TH")
		XCTAssertEqual(textfield.text, "2 123 4567")
		textfield.set(phoneNumber: "+6702112345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+670")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TL")
		XCTAssertEqual(textfield.text, "211 2345")
		textfield.set(phoneNumber: "+22822212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+228")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TG")
		XCTAssertEqual(textfield.text, "22 21 23 45")
		textfield.set(phoneNumber: "+6903101")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+690")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TK")
		XCTAssertEqual(textfield.text, "3101")
		textfield.set(phoneNumber: "+67620123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+676")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TO")
		XCTAssertEqual(textfield.text, "20-123")
		textfield.set(phoneNumber: "+18682211234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TT")
		XCTAssertEqual(textfield.text, "868-221-1234")
		textfield.set(phoneNumber: "+21671234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+216")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TN")
		XCTAssertEqual(textfield.text, "71 234 567")
		textfield.set(phoneNumber: "+99312345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+993")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TM")
		XCTAssertEqual(textfield.text, "12 34-56-78")
		textfield.set(phoneNumber: "+902123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+90")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TR")
		XCTAssertEqual(textfield.text, "212 345 67 89")
		textfield.set(phoneNumber: "+68820123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+688")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TV")
		XCTAssertEqual(textfield.text, "20123")
		textfield.set(phoneNumber: "+380311234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+380")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "UA")
		XCTAssertEqual(textfield.text, "3112 34567")
		textfield.set(phoneNumber: "+59821231234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+598")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "UY")
		XCTAssertEqual(textfield.text, "2123 1234")
		textfield.set(phoneNumber: "+67822123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+678")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VU")
		XCTAssertEqual(textfield.text, "22123")
		textfield.set(phoneNumber: "+582121234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+58")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VE")
		XCTAssertEqual(textfield.text, "212-1234567")
		textfield.set(phoneNumber: "+842101234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+84")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VN")
		XCTAssertEqual(textfield.text, "210 1234 567")
		textfield.set(phoneNumber: "+681501234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+681")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "WF")
		XCTAssertEqual(textfield.text, "50 12 34")
		textfield.set(phoneNumber: "+9671234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+967")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "YE")
		XCTAssertEqual(textfield.text, "1 234 567")
		textfield.set(phoneNumber: "+260211234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+260")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ZM")
		XCTAssertEqual(textfield.text, "21 1234567")
		textfield.set(phoneNumber: "+2631312345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+263")
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ZW")
		XCTAssertEqual(textfield.text, "13 12345")
	}

	func testSetFlag() {
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AF")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AF")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AL")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AL")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "DZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AS")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AS")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AD")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AD")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AW")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AW")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AU")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AU")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AX")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AX")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BS")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BS")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BH")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BH")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BD")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BD")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BB")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BB")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BY")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BY")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BJ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BJ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BW")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BW")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "IO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "VG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BF")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BF")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KH")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KH")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CV")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CV")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KY")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KY")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CF")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CF")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TD")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TD")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CL")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CL")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CX")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CX")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CC")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CC")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CD")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CD")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CK")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CK")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "HR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CU")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CU")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CY")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CY")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "DK")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DK")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "DJ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DJ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "DM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "DO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "EC")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "EC")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "EG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "EG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SV")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SV")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GQ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GQ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ER")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ER")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "EE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "EE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ET")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ET")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "FK")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FK")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "FO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "FJ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FJ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "FI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "FR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GF")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GF")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PF")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PF")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "DE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "DE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GH")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GH")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GL")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GL")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GD")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GD")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GP")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GP")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GU")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GU")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GW")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GW")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GY")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GY")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "HT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "HN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "HK")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HK")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "HU")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "HU")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "IS")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IS")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "IN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ID")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ID")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "IR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "IQ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IQ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "IE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "IM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "IL")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IL")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "IT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "IT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "JM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "JM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "JP")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "JP")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "JE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "JE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "JO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "JO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KW")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KW")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LV")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LV")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LB")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LB")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LS")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LS")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LY")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LY")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LU")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LU")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MK")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MK")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MW")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MW")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MY")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MY")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MV")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MV")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ML")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ML")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MH")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MH")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MQ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MQ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MU")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MU")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "YT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "YT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MX")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MX")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "FM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "FM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MD")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MD")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MC")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MC")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ME")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ME")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MS")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MS")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NP")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NP")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NL")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NL")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NC")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NC")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NU")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NU")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NF")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NF")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KP")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KP")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MP")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MP")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "NO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "NO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "OM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "OM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PK")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PK")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PW")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PW")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PS")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PS")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PY")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PY")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PH")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PH")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PL")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PL")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "QA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "QA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "RE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "RO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "RU")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RU")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "RW")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RW")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "WS")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "WS")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ST")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ST")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "RS")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "RS")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SC")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SC")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SL")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SL")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SK")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SK")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SB")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SB")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ZA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ZA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SS")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SS")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ES")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ES")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LK")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LK")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "BL")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "BL")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SH")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SH")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "KN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "KN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "LC")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "LC")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "MF")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "MF")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "PM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "PM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "VC")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VC")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SD")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SD")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SJ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SJ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "CH")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "CH")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "SY")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "SY")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TW")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TW")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TJ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TJ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TH")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TH")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TL")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TL")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TK")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TK")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TO")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TO")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TT")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TT")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TR")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TR")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TC")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TC")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "TV")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "TV")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "VI")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VI")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "UG")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "UG")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "UA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "UA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "AE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "AE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "GB")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "GB")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "US")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "US")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "UY")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "UY")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "UZ")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "UZ")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "VU")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VU")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "VA")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VA")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "VE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "VN")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "VN")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "WF")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "WF")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "YE")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "YE")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ZM")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ZM")
		textfield.setFlag(countryCode: FPNCountryCode(rawValue: "ZW")!)
		XCTAssertEqual(textfield.selectedCountry?.code.rawValue, "ZW")
	}
}
