platform :ios, '9.0'
use_frameworks!

target 'CTKFlagPhoneNumber_Example' do
  pod 'CTKFlagPhoneNumber', :path => '../'
end

target 'CTKFlagPhoneNumber_ExampleTests' do
	pod 'CTKFlagPhoneNumber', :path => '../'
end
