platform :ios, '9.0'
use_frameworks!

target 'FlagPhoneNumber_Example' do
  pod 'FlagPhoneNumber', :path => '../'
end

target 'FlagPhoneNumber_ExampleTests' do
	pod 'FlagPhoneNumber', :path => '../'
	pod 'SwiftLint'
end
