//
//  FPNOBJCCountryKey.swift
//  FlagPhoneNumber
//
//  Created by Aurelien on 20/05/2019.
//

import Foundation

@objc public enum FPNOBJCCountryKey: Int {
	case AF
	case ZA
	case AL
	case DZ
	case DE
	case AD
	case AO
	case AI
	case AG
	case SA
	case AR
	case AM
	case AW
	case AU
	case AT
	case AZ
	case BS
	case BH
	case BD
	case BB
	case BE
	case BZ
	case BM
	case BT
	case BY
	case BO
	case BA
	case BW
	case BN
	case BR
	case BG
	case BF
	case BI
	case BJ
	case KH
	case CM
	case CA
	case CV
	case CL
	case CN
	case CY
	case CO
	case KM
	case CG
	case CD
	case KP
	case KR
	case CR
	case HR
	case CU
	case CI
	case DK
	case DJ
	case DM
	case ES
	case EE
	case FJ
	case FI
	case FR
	case GA
	case GM
	case GH
	case GI
	case GD
	case GL
	case GR
	case GP
	case GU
	case GT
	case GG
	case GN
	case GQ
	case GW
	case GY
	case GF
	case GE
	case HT
	case HN
	case HK
	case HU
	case IN
	case ID
	case IQ
	case IR
	case IE
	case IS
	case IL
	case IT
	case JM
	case JP
	case JE
	case JO
	case KZ
	case KE
	case KG
	case KI
	case KW
	case RE
	case LA
	case LS
	case LV
	case LB
	case LY
	case LR
	case LI
	case LT
	case LU
	case MO
	case MK
	case MG
	case MY
	case MW
	case MV
	case ML
	case MT
	case MA
	case MQ
	case MU
	case MR
	case YT
	case MX
	case MD
	case MC
	case MN
	case MS
	case ME
	case MZ
	case MM
	case NA
	case NR
	case NI
	case NE
	case NG
	case NU
	case NO
	case NC
	case NZ
	case NP
	case OM
	case UG
	case UZ
	case PK
	case PW
	case PA
	case PG
	case PY
	case NL
	case PH
	case PL
	case PF
	case PR
	case PT
	case PE
	case QA
	case RO
	case GB
	case RU
	case RW
	case CF
	case DO
	case BL
	case KN
	case SM
	case MF
	case PM
	case VC
	case SH
	case LC
	case SV
	case WS
	case AS
	case ST
	case RS
	case SC
	case SL
	case SG
	case SK
	case SI
	case SO
	case SD
	case SS
	case LK
	case CH
	case SR
	case SE
	case SJ
	case SZ
	case SY
	case SN
	case TJ
	case TZ
	case TW
	case TD
	case CZ
	case IO
	case PS
	case TH
	case TL
	case TG
	case TK
	case TO
	case TT
	case TN
	case TM
	case TR
	case TV
	case UA
	case UY
	case VU
	case VE
	case VN
	case WF
	case YE
	case ZM
	case ZW
	case EG
	case AE
	case EC
	case ER
	case VA
	case FM
	case US
	case ET
	case CX
	case NF
	case IM
	case KY
	case CC
	case CK
	case FO
	case FK
	case MP
	case MH
	case SB
	case TC
	case VG
	case VI
	case AX
}

public let FPNOBJCCountryCode: [FPNOBJCCountryKey: String] = [
	FPNOBJCCountryKey.AF: "AF",
	FPNOBJCCountryKey.ZA: "ZA",
	FPNOBJCCountryKey.AL: "AL",
	FPNOBJCCountryKey.DZ: "DZ",
	FPNOBJCCountryKey.DE: "DE",
	FPNOBJCCountryKey.AD: "AD",
	FPNOBJCCountryKey.AO: "AO",
	FPNOBJCCountryKey.AI: "AI",
	FPNOBJCCountryKey.AG: "AG",
	FPNOBJCCountryKey.SA: "SA",
	FPNOBJCCountryKey.AR: "AR",
	FPNOBJCCountryKey.AM: "AM",
	FPNOBJCCountryKey.AW: "AW",
	FPNOBJCCountryKey.AU: "AU",
	FPNOBJCCountryKey.AT: "AT",
	FPNOBJCCountryKey.AZ: "AZ",
	FPNOBJCCountryKey.BS: "BS",
	FPNOBJCCountryKey.BH: "BH",
	FPNOBJCCountryKey.BD: "BD",
	FPNOBJCCountryKey.BB: "BB",
	FPNOBJCCountryKey.BE: "BE",
	FPNOBJCCountryKey.BZ: "BZ",
	FPNOBJCCountryKey.BM: "BM",
	FPNOBJCCountryKey.BT: "BT",
	FPNOBJCCountryKey.BY: "BY",
	FPNOBJCCountryKey.BO: "BO",
	FPNOBJCCountryKey.BA: "BA",
	FPNOBJCCountryKey.BW: "BW",
	FPNOBJCCountryKey.BN: "BN",
	FPNOBJCCountryKey.BR: "BR",
	FPNOBJCCountryKey.BG: "BG",
	FPNOBJCCountryKey.BF: "BF",
	FPNOBJCCountryKey.BI: "BI",
	FPNOBJCCountryKey.BJ: "BJ",
	FPNOBJCCountryKey.KH: "KH",
	FPNOBJCCountryKey.CM: "CM",
	FPNOBJCCountryKey.CA: "CA",
	FPNOBJCCountryKey.CV: "CV",
	FPNOBJCCountryKey.CL: "CL",
	FPNOBJCCountryKey.CN: "CN",
	FPNOBJCCountryKey.CY: "CY",
	FPNOBJCCountryKey.CO: "CO",
	FPNOBJCCountryKey.KM: "KM",
	FPNOBJCCountryKey.CG: "CG",
	FPNOBJCCountryKey.CD: "CD",
	FPNOBJCCountryKey.KP: "KP",
	FPNOBJCCountryKey.KR: "KR",
	FPNOBJCCountryKey.CR: "CR",
	FPNOBJCCountryKey.HR: "HR",
	FPNOBJCCountryKey.CU: "CU",
	FPNOBJCCountryKey.CI: "CI",
	FPNOBJCCountryKey.DK: "DK",
	FPNOBJCCountryKey.DJ: "DJ",
	FPNOBJCCountryKey.DM: "DM",
	FPNOBJCCountryKey.ES: "ES",
	FPNOBJCCountryKey.EE: "EE",
	FPNOBJCCountryKey.FJ: "FJ",
	FPNOBJCCountryKey.FI: "FI",
	FPNOBJCCountryKey.FR: "FR",
	FPNOBJCCountryKey.GA: "GA",
	FPNOBJCCountryKey.GM: "GM",
	FPNOBJCCountryKey.GH: "GH",
	FPNOBJCCountryKey.GI: "GI",
	FPNOBJCCountryKey.GD: "GD",
	FPNOBJCCountryKey.GL: "GL",
	FPNOBJCCountryKey.GR: "GR",
	FPNOBJCCountryKey.GP: "GP",
	FPNOBJCCountryKey.GU: "GU",
	FPNOBJCCountryKey.GT: "GT",
	FPNOBJCCountryKey.GG: "GG",
	FPNOBJCCountryKey.GN: "GN",
	FPNOBJCCountryKey.GQ: "GQ",
	FPNOBJCCountryKey.GW: "GW",
	FPNOBJCCountryKey.GY: "GY",
	FPNOBJCCountryKey.GF: "GF",
	FPNOBJCCountryKey.GE: "GE",
	FPNOBJCCountryKey.HT: "HT",
	FPNOBJCCountryKey.HN: "HN",
	FPNOBJCCountryKey.HK: "HK",
	FPNOBJCCountryKey.HU: "HU",
	FPNOBJCCountryKey.IN: "IN",
	FPNOBJCCountryKey.ID: "ID",
	FPNOBJCCountryKey.IQ: "IQ",
	FPNOBJCCountryKey.IR: "IR",
	FPNOBJCCountryKey.IE: "IE",
	FPNOBJCCountryKey.IS: "IS",
	FPNOBJCCountryKey.IL: "IL",
	FPNOBJCCountryKey.IT: "IT",
	FPNOBJCCountryKey.JM: "JM",
	FPNOBJCCountryKey.JP: "JP",
	FPNOBJCCountryKey.JE: "JE",
	FPNOBJCCountryKey.JO: "JO",
	FPNOBJCCountryKey.KZ: "KZ",
	FPNOBJCCountryKey.KE: "KE",
	FPNOBJCCountryKey.KG: "KG",
	FPNOBJCCountryKey.KI: "KI",
	FPNOBJCCountryKey.KW: "KW",
	FPNOBJCCountryKey.RE: "RE",
	FPNOBJCCountryKey.LA: "LA",
	FPNOBJCCountryKey.LS: "LS",
	FPNOBJCCountryKey.LV: "LV",
	FPNOBJCCountryKey.LB: "LB",
	FPNOBJCCountryKey.LY: "LY",
	FPNOBJCCountryKey.LR: "LR",
	FPNOBJCCountryKey.LI: "LI",
	FPNOBJCCountryKey.LT: "LT",
	FPNOBJCCountryKey.LU: "LU",
	FPNOBJCCountryKey.MO: "MO",
	FPNOBJCCountryKey.MK: "MK",
	FPNOBJCCountryKey.MG: "MG",
	FPNOBJCCountryKey.MY: "MY",
	FPNOBJCCountryKey.MW: "MW",
	FPNOBJCCountryKey.MV: "MV",
	FPNOBJCCountryKey.ML: "ML",
	FPNOBJCCountryKey.MT: "MT",
	FPNOBJCCountryKey.MA: "MA",
	FPNOBJCCountryKey.MQ: "MQ",
	FPNOBJCCountryKey.MU: "MU",
	FPNOBJCCountryKey.MR: "MR",
	FPNOBJCCountryKey.YT: "YT",
	FPNOBJCCountryKey.MX: "MX",
	FPNOBJCCountryKey.MD: "MD",
	FPNOBJCCountryKey.MC: "MC",
	FPNOBJCCountryKey.MN: "MN",
	FPNOBJCCountryKey.MS: "MS",
	FPNOBJCCountryKey.ME: "ME",
	FPNOBJCCountryKey.MZ: "MZ",
	FPNOBJCCountryKey.MM: "MM",
	FPNOBJCCountryKey.NA: "NA",
	FPNOBJCCountryKey.NR: "NR",
	FPNOBJCCountryKey.NI: "NI",
	FPNOBJCCountryKey.NE: "NE",
	FPNOBJCCountryKey.NG: "NG",
	FPNOBJCCountryKey.NU: "NU",
	FPNOBJCCountryKey.NO: "NO",
	FPNOBJCCountryKey.NC: "NC",
	FPNOBJCCountryKey.NZ: "NZ",
	FPNOBJCCountryKey.NP: "NP",
	FPNOBJCCountryKey.OM: "OM",
	FPNOBJCCountryKey.UG: "UG",
	FPNOBJCCountryKey.UZ: "UZ",
	FPNOBJCCountryKey.PK: "PK",
	FPNOBJCCountryKey.PW: "PW",
	FPNOBJCCountryKey.PA: "PA",
	FPNOBJCCountryKey.PG: "PG",
	FPNOBJCCountryKey.PY: "PY",
	FPNOBJCCountryKey.NL: "NL",
	FPNOBJCCountryKey.PH: "PH",
	FPNOBJCCountryKey.PL: "PL",
	FPNOBJCCountryKey.PF: "PF",
	FPNOBJCCountryKey.PR: "PR",
	FPNOBJCCountryKey.PT: "PT",
	FPNOBJCCountryKey.PE: "PE",
	FPNOBJCCountryKey.QA: "QA",
	FPNOBJCCountryKey.RO: "RO",
	FPNOBJCCountryKey.GB: "GB",
	FPNOBJCCountryKey.RU: "RU",
	FPNOBJCCountryKey.RW: "RW",
	FPNOBJCCountryKey.CF: "CF",
	FPNOBJCCountryKey.DO: "DO",
	FPNOBJCCountryKey.BL: "BL",
	FPNOBJCCountryKey.KN: "KN",
	FPNOBJCCountryKey.SM: "SM",
	FPNOBJCCountryKey.MF: "MF",
	FPNOBJCCountryKey.PM: "PM",
	FPNOBJCCountryKey.VC: "VC",
	FPNOBJCCountryKey.SH: "SH",
	FPNOBJCCountryKey.LC: "LC",
	FPNOBJCCountryKey.SV: "SV",
	FPNOBJCCountryKey.WS: "WS",
	FPNOBJCCountryKey.AS: "AS",
	FPNOBJCCountryKey.ST: "ST",
	FPNOBJCCountryKey.RS: "RS",
	FPNOBJCCountryKey.SC: "SC",
	FPNOBJCCountryKey.SL: "SL",
	FPNOBJCCountryKey.SG: "SG",
	FPNOBJCCountryKey.SK: "SK",
	FPNOBJCCountryKey.SI: "SI",
	FPNOBJCCountryKey.SO: "SO",
	FPNOBJCCountryKey.SD: "SD",
	FPNOBJCCountryKey.SS: "SS",
	FPNOBJCCountryKey.LK: "LK",
	FPNOBJCCountryKey.CH: "CH",
	FPNOBJCCountryKey.SR: "SR",
	FPNOBJCCountryKey.SE: "SE",
	FPNOBJCCountryKey.SJ: "SJ",
	FPNOBJCCountryKey.SZ: "SZ",
	FPNOBJCCountryKey.SY: "SY",
	FPNOBJCCountryKey.SN: "SN",
	FPNOBJCCountryKey.TJ: "TJ",
	FPNOBJCCountryKey.TZ: "TZ",
	FPNOBJCCountryKey.TW: "TW",
	FPNOBJCCountryKey.TD: "TD",
	FPNOBJCCountryKey.CZ: "CZ",
	FPNOBJCCountryKey.IO: "IO",
	FPNOBJCCountryKey.PS: "PS",
	FPNOBJCCountryKey.TH: "TH",
	FPNOBJCCountryKey.TL: "TL",
	FPNOBJCCountryKey.TG: "TG",
	FPNOBJCCountryKey.TK: "TK",
	FPNOBJCCountryKey.TO: "TO",
	FPNOBJCCountryKey.TT: "TT",
	FPNOBJCCountryKey.TN: "TN",
	FPNOBJCCountryKey.TM: "TM",
	FPNOBJCCountryKey.TR: "TR",
	FPNOBJCCountryKey.TV: "TV",
	FPNOBJCCountryKey.UA: "UA",
	FPNOBJCCountryKey.UY: "UY",
	FPNOBJCCountryKey.VU: "VU",
	FPNOBJCCountryKey.VE: "VE",
	FPNOBJCCountryKey.VN: "VN",
	FPNOBJCCountryKey.WF: "WF",
	FPNOBJCCountryKey.YE: "YE",
	FPNOBJCCountryKey.ZM: "ZM",
	FPNOBJCCountryKey.ZW: "ZW",
	FPNOBJCCountryKey.EG: "EG",
	FPNOBJCCountryKey.AE: "AE",
	FPNOBJCCountryKey.EC: "EC",
	FPNOBJCCountryKey.ER: "ER",
	FPNOBJCCountryKey.VA: "VA",
	FPNOBJCCountryKey.FM: "FM",
	FPNOBJCCountryKey.US: "US",
	FPNOBJCCountryKey.ET: "ET",
	FPNOBJCCountryKey.CX: "CX",
	FPNOBJCCountryKey.NF: "NF",
	FPNOBJCCountryKey.IM: "IM",
	FPNOBJCCountryKey.KY: "KY",
	FPNOBJCCountryKey.CC: "CC",
	FPNOBJCCountryKey.CK: "CK",
	FPNOBJCCountryKey.FO: "FO",
	FPNOBJCCountryKey.FK: "FK",
	FPNOBJCCountryKey.MP: "MP",
	FPNOBJCCountryKey.MH: "MH",
	FPNOBJCCountryKey.SB: "SB",
	FPNOBJCCountryKey.TC: "TC",
	FPNOBJCCountryKey.VG: "VG",
	FPNOBJCCountryKey.VI: "VI",
	FPNOBJCCountryKey.AX: "AX"
]
