//
//  FlagPhoneNumber_ExampleTests.swift
//  FlagPhoneNumber
//
//  Created by Aurélien Grifasi on 06/08/2017.
//  Copyright (c) 2017 Aurélien Grifasi. All rights reserved.
//

import XCTest
@testable import FlagPhoneNumber

class FlagPhoneNumber_ExampleTests: XCTestCase {

	let textfield = FPNTextField()

	override func setUp() {
		super.setUp()
		//		Put setup code here. This method is called before the invocation of each test method in the class.
	}

	override func tearDown() {
		//		Put teardown code here. This method is called after the invocation of each test method in the class.
		super.tearDown()
	}

	func testSetFlagAndPhoneNumber() {
		textfield.setFlag(for: "FR")
		textfield.set(phoneNumber: "0600000000")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+33")
		XCTAssertEqual(textfield.selectedCountry?.code, "FR")
		XCTAssertEqual(textfield.text, "6 00 00 00 00")
	}

	func testSetPhoneNumber() {
		textfield.set(phoneNumber: "+93234567890")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+93")
		XCTAssertEqual(textfield.selectedCountry?.code, "AF")
		XCTAssertEqual(textfield.text, "23 456 7890")
		textfield.set(phoneNumber: "+27101234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+27")
		XCTAssertEqual(textfield.selectedCountry?.code, "ZA")
		XCTAssertEqual(textfield.text, "10 123 4567")
		textfield.set(phoneNumber: "+35522345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+355")
		XCTAssertEqual(textfield.selectedCountry?.code, "AL")
		XCTAssertEqual(textfield.text, "22 345 678")
		textfield.set(phoneNumber: "+21312345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+213")
		XCTAssertEqual(textfield.selectedCountry?.code, "DZ")
		XCTAssertEqual(textfield.text, "12 34 56 78")
		textfield.set(phoneNumber: "+4930123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+49")
		XCTAssertEqual(textfield.selectedCountry?.code, "DE")
		XCTAssertEqual(textfield.text, "30 123456")
		textfield.set(phoneNumber: "+376712345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+376")
		XCTAssertEqual(textfield.selectedCountry?.code, "AD")
		XCTAssertEqual(textfield.text, "712 345")
		textfield.set(phoneNumber: "+244222123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+244")
		XCTAssertEqual(textfield.selectedCountry?.code, "AO")
		XCTAssertEqual(textfield.text, "222 123 456")
		textfield.set(phoneNumber: "+12644612345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "AI")
		XCTAssertEqual(textfield.text, "264-461-2345")
		textfield.set(phoneNumber: "+12684601234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "AG")
		XCTAssertEqual(textfield.text, "268-460-1234")
		textfield.set(phoneNumber: "+966112345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+966")
		XCTAssertEqual(textfield.selectedCountry?.code, "SA")
		XCTAssertEqual(textfield.text, "11 234 5678")
		textfield.set(phoneNumber: "+541123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+54")
		XCTAssertEqual(textfield.selectedCountry?.code, "AR")
		XCTAssertEqual(textfield.text, "11 2345-6789")
		textfield.set(phoneNumber: "+37410123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+374")
		XCTAssertEqual(textfield.selectedCountry?.code, "AM")
		XCTAssertEqual(textfield.text, "10 123456")
		textfield.set(phoneNumber: "+2975212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+297")
		XCTAssertEqual(textfield.selectedCountry?.code, "AW")
		XCTAssertEqual(textfield.text, "521 2345")
		textfield.set(phoneNumber: "+61212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+61")
		XCTAssertEqual(textfield.selectedCountry?.code, "AU")
		XCTAssertEqual(textfield.text, "2 1234 5678")
		textfield.set(phoneNumber: "+431234567890")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+43")
		XCTAssertEqual(textfield.selectedCountry?.code, "AT")
		XCTAssertEqual(textfield.text, "1 234567890")
		textfield.set(phoneNumber: "+994123123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+994")
		XCTAssertEqual(textfield.selectedCountry?.code, "AZ")
		XCTAssertEqual(textfield.text, "12 312 34 56")
		textfield.set(phoneNumber: "+12423456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "BS")
		XCTAssertEqual(textfield.text, "242-345-6789")
		textfield.set(phoneNumber: "+97317001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+973")
		XCTAssertEqual(textfield.selectedCountry?.code, "BH")
		XCTAssertEqual(textfield.text, "1700 1234")
		textfield.set(phoneNumber: "+88027111234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+880")
		XCTAssertEqual(textfield.selectedCountry?.code, "BD")
		XCTAssertEqual(textfield.text, "2-7111234")
		textfield.set(phoneNumber: "+12464123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "BB")
		XCTAssertEqual(textfield.text, "246-412-3456")
		textfield.set(phoneNumber: "+3212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+32")
		XCTAssertEqual(textfield.selectedCountry?.code, "BE")
		XCTAssertEqual(textfield.text, "12 34 56 78")
		textfield.set(phoneNumber: "+5012221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+501")
		XCTAssertEqual(textfield.selectedCountry?.code, "BZ")
		XCTAssertEqual(textfield.text, "222-1234")
		textfield.set(phoneNumber: "+14412345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "BM")
		XCTAssertEqual(textfield.text, "441-234-5678")
		textfield.set(phoneNumber: "+22920211234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+229")
		XCTAssertEqual(textfield.selectedCountry?.code, "BJ")
		XCTAssertEqual(textfield.text, "20 21 12 34")
		textfield.set(phoneNumber: "+9752345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+975")
		XCTAssertEqual(textfield.selectedCountry?.code, "BT")
		XCTAssertEqual(textfield.text, "2 345 678")
		textfield.set(phoneNumber: "+375152450911")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+375")
		XCTAssertEqual(textfield.selectedCountry?.code, "BY")
		XCTAssertEqual(textfield.text, "152 45-09-11")
		textfield.set(phoneNumber: "+59122123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+591")
		XCTAssertEqual(textfield.selectedCountry?.code, "BO")
		XCTAssertEqual(textfield.text, "2 2123456")
		textfield.set(phoneNumber: "+38730123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+387")
		XCTAssertEqual(textfield.selectedCountry?.code, "BA")
		XCTAssertEqual(textfield.text, "30 123-456")
		textfield.set(phoneNumber: "+2672401234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+267")
		XCTAssertEqual(textfield.selectedCountry?.code, "BW")
		XCTAssertEqual(textfield.text, "240 1234")
		textfield.set(phoneNumber: "+551123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+55")
		XCTAssertEqual(textfield.selectedCountry?.code, "BR")
		XCTAssertEqual(textfield.text, "11 2345-6789")
		textfield.set(phoneNumber: "+6732345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+673")
		XCTAssertEqual(textfield.selectedCountry?.code, "BN")
		XCTAssertEqual(textfield.text, "234 5678")
		textfield.set(phoneNumber: "+3592123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+359")
		XCTAssertEqual(textfield.selectedCountry?.code, "BG")
		XCTAssertEqual(textfield.text, "2 123 456")
		textfield.set(phoneNumber: "+22620491234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+226")
		XCTAssertEqual(textfield.selectedCountry?.code, "BF")
		XCTAssertEqual(textfield.text, "20 49 12 34")
		textfield.set(phoneNumber: "+25722201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+257")
		XCTAssertEqual(textfield.selectedCountry?.code, "BI")
		XCTAssertEqual(textfield.text, "22 20 12 34")
		textfield.set(phoneNumber: "+85523756789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+855")
		XCTAssertEqual(textfield.selectedCountry?.code, "KH")
		XCTAssertEqual(textfield.text, "23 756 789")
		textfield.set(phoneNumber: "+237222123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+237")
		XCTAssertEqual(textfield.selectedCountry?.code, "CM")
		XCTAssertEqual(textfield.text, "2 22 12 34 56")
		textfield.set(phoneNumber: "+12042345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "CA")
		XCTAssertEqual(textfield.text, "204-234-5678")
		textfield.set(phoneNumber: "+2382211234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+238")
		XCTAssertEqual(textfield.selectedCountry?.code, "CV")
		XCTAssertEqual(textfield.text, "221 12 34")
		textfield.set(phoneNumber: "+56221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+56")
		XCTAssertEqual(textfield.selectedCountry?.code, "CL")
		XCTAssertEqual(textfield.text, "2 2123 4567")
		textfield.set(phoneNumber: "+861012345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+86")
		XCTAssertEqual(textfield.selectedCountry?.code, "CN")
		XCTAssertEqual(textfield.text, "10 1234 5678")
		textfield.set(phoneNumber: "+35722345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+357")
		XCTAssertEqual(textfield.selectedCountry?.code, "CY")
		XCTAssertEqual(textfield.text, "22 345678")
		textfield.set(phoneNumber: "+5712345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+57")
		XCTAssertEqual(textfield.selectedCountry?.code, "CO")
		XCTAssertEqual(textfield.text, "1 2345678")
		textfield.set(phoneNumber: "+2697712345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+269")
		XCTAssertEqual(textfield.selectedCountry?.code, "KM")
		XCTAssertEqual(textfield.text, "771 23 45")
		textfield.set(phoneNumber: "+242222123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+242")
		XCTAssertEqual(textfield.selectedCountry?.code, "CG")
		XCTAssertEqual(textfield.text, "22 212 3456")
		textfield.set(phoneNumber: "+2431234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+243")
		XCTAssertEqual(textfield.selectedCountry?.code, "CD")
		XCTAssertEqual(textfield.text, "12 34567")
		textfield.set(phoneNumber: "+85021234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+850")
		XCTAssertEqual(textfield.selectedCountry?.code, "KP")
		XCTAssertEqual(textfield.text, "2 123 4567")
		textfield.set(phoneNumber: "+8222123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+82")
		XCTAssertEqual(textfield.selectedCountry?.code, "KR")
		XCTAssertEqual(textfield.text, "2-212-3456")
		textfield.set(phoneNumber: "+50622123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+506")
		XCTAssertEqual(textfield.selectedCountry?.code, "CR")
		XCTAssertEqual(textfield.text, "2212 3456")
		textfield.set(phoneNumber: "+22521234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+225")
		XCTAssertEqual(textfield.selectedCountry?.code, "CI")
		XCTAssertEqual(textfield.text, "21 23 45 67")
		textfield.set(phoneNumber: "+38512345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+385")
		XCTAssertEqual(textfield.selectedCountry?.code, "HR")
		XCTAssertEqual(textfield.text, "1 2345 678")
		textfield.set(phoneNumber: "+5371234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+53")
		XCTAssertEqual(textfield.selectedCountry?.code, "CU")
		XCTAssertEqual(textfield.text, "7 1234567")
		textfield.set(phoneNumber: "+4532123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+45")
		XCTAssertEqual(textfield.selectedCountry?.code, "DK")
		XCTAssertEqual(textfield.text, "32 12 34 56")
		textfield.set(phoneNumber: "+25321360003")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+253")
		XCTAssertEqual(textfield.selectedCountry?.code, "DJ")
		XCTAssertEqual(textfield.text, "21 36 00 03")
		textfield.set(phoneNumber: "+17674201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "DM")
		XCTAssertEqual(textfield.text, "767-420-1234")
		textfield.set(phoneNumber: "+50321234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+503")
		XCTAssertEqual(textfield.selectedCountry?.code, "SV")
		XCTAssertEqual(textfield.text, "2123 4567")
		textfield.set(phoneNumber: "+34810123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+34")
		XCTAssertEqual(textfield.selectedCountry?.code, "ES")
		XCTAssertEqual(textfield.text, "810 12 34 56")
		textfield.set(phoneNumber: "+3723212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+372")
		XCTAssertEqual(textfield.selectedCountry?.code, "EE")
		XCTAssertEqual(textfield.text, "321 2345")
		textfield.set(phoneNumber: "+20234567890")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+20")
		XCTAssertEqual(textfield.selectedCountry?.code, "EG")
		XCTAssertEqual(textfield.text, "2 34567890")
		textfield.set(phoneNumber: "+97122345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+971")
		XCTAssertEqual(textfield.selectedCountry?.code, "AE")
		XCTAssertEqual(textfield.text, "2 234 5678")
		textfield.set(phoneNumber: "+59322123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+593")
		XCTAssertEqual(textfield.selectedCountry?.code, "EC")
		XCTAssertEqual(textfield.text, "2-212-3456")
		textfield.set(phoneNumber: "+2918370362")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+291")
		XCTAssertEqual(textfield.selectedCountry?.code, "ER")
		XCTAssertEqual(textfield.text, "8 370 362")
//		textfield.set(phoneNumber: "+39669812345")
//		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+39")
//		XCTAssertEqual(textfield.selectedCountry?.code, "VA")
//		XCTAssertEqual(textfield.text, "6 6981 2345")
		textfield.set(phoneNumber: "+6913201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+691")
		XCTAssertEqual(textfield.selectedCountry?.code, "FM")
		XCTAssertEqual(textfield.text, "320 1234")
		textfield.set(phoneNumber: "+12015550123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "US")
		XCTAssertEqual(textfield.text, "201-555-0123")
		textfield.set(phoneNumber: "+251111112345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+251")
		XCTAssertEqual(textfield.selectedCountry?.code, "ET")
		XCTAssertEqual(textfield.text, "11 111 2345")
		textfield.set(phoneNumber: "+6793212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+679")
		XCTAssertEqual(textfield.selectedCountry?.code, "FJ")
		XCTAssertEqual(textfield.text, "321 2345")
		textfield.set(phoneNumber: "+358131234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+358")
		XCTAssertEqual(textfield.selectedCountry?.code, "FI")
		XCTAssertEqual(textfield.text, "13 1234567")
		textfield.set(phoneNumber: "+33123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+33")
		XCTAssertEqual(textfield.selectedCountry?.code, "FR")
		XCTAssertEqual(textfield.text, "1 23 45 67 89")
		textfield.set(phoneNumber: "+2414422222")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+241")
		XCTAssertEqual(textfield.selectedCountry?.code, "GA")
		XCTAssertEqual(textfield.text, "4 42 22 22")
		textfield.set(phoneNumber: "+2205661234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+220")
		XCTAssertEqual(textfield.selectedCountry?.code, "GM")
		XCTAssertEqual(textfield.text, "566 1234")
		textfield.set(phoneNumber: "+995322123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+995")
		XCTAssertEqual(textfield.selectedCountry?.code, "GE")
		XCTAssertEqual(textfield.text, "322 12 34 56")
		textfield.set(phoneNumber: "+233302345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+233")
		XCTAssertEqual(textfield.selectedCountry?.code, "GH")
		XCTAssertEqual(textfield.text, "30 234 5678")
		textfield.set(phoneNumber: "+35020012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+350")
		XCTAssertEqual(textfield.selectedCountry?.code, "GI")
		XCTAssertEqual(textfield.text, "200 12345")
		textfield.set(phoneNumber: "+14732691234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "GD")
		XCTAssertEqual(textfield.text, "473-269-1234")
		textfield.set(phoneNumber: "+302123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+30")
		XCTAssertEqual(textfield.selectedCountry?.code, "GR")
		XCTAssertEqual(textfield.text, "21 2345 6789")
		textfield.set(phoneNumber: "+299321000")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+299")
		XCTAssertEqual(textfield.selectedCountry?.code, "GL")
		XCTAssertEqual(textfield.text, "32 10 00")
		textfield.set(phoneNumber: "+590590201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+590")
		XCTAssertEqual(textfield.selectedCountry?.code, "GP")
		XCTAssertEqual(textfield.text, "590 20-1234")
		textfield.set(phoneNumber: "+16713001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "GU")
		XCTAssertEqual(textfield.text, "671-300-1234")
		textfield.set(phoneNumber: "+50222456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+502")
		XCTAssertEqual(textfield.selectedCountry?.code, "GT")
		XCTAssertEqual(textfield.text, "2245 6789")
		textfield.set(phoneNumber: "+441481256789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+44")
		XCTAssertEqual(textfield.selectedCountry?.code, "GG")
		XCTAssertEqual(textfield.text, "1481 256789")
		textfield.set(phoneNumber: "+22430241234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+224")
		XCTAssertEqual(textfield.selectedCountry?.code, "GN")
		XCTAssertEqual(textfield.text, "30 24 12 34")
		textfield.set(phoneNumber: "+240333091234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+240")
		XCTAssertEqual(textfield.selectedCountry?.code, "GQ")
		XCTAssertEqual(textfield.text, "333 091 234")
		textfield.set(phoneNumber: "+245443201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+245")
		XCTAssertEqual(textfield.selectedCountry?.code, "GW")
		XCTAssertEqual(textfield.text, "443 201 234")
		textfield.set(phoneNumber: "+5922201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+592")
		XCTAssertEqual(textfield.selectedCountry?.code, "GY")
		XCTAssertEqual(textfield.text, "220 1234")
		textfield.set(phoneNumber: "+594594101234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+594")
		XCTAssertEqual(textfield.selectedCountry?.code, "GF")
		XCTAssertEqual(textfield.text, "594 10 12 34")
		textfield.set(phoneNumber: "+50922453300")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+509")
		XCTAssertEqual(textfield.selectedCountry?.code, "HT")
		XCTAssertEqual(textfield.text, "22 45 3300")
		textfield.set(phoneNumber: "+50422123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+504")
		XCTAssertEqual(textfield.selectedCountry?.code, "HN")
		XCTAssertEqual(textfield.text, "2212-3456")
		textfield.set(phoneNumber: "+85221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+852")
		XCTAssertEqual(textfield.selectedCountry?.code, "HK")
		XCTAssertEqual(textfield.text, "2123 4567")
		textfield.set(phoneNumber: "+3612345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+36")
		XCTAssertEqual(textfield.selectedCountry?.code, "HU")
		XCTAssertEqual(textfield.text, "1 234 5678")
		textfield.set(phoneNumber: "+911123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+91")
		XCTAssertEqual(textfield.selectedCountry?.code, "IN")
		XCTAssertEqual(textfield.text, "11 2345 6789")
		textfield.set(phoneNumber: "+62612345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+62")
		XCTAssertEqual(textfield.selectedCountry?.code, "ID")
		XCTAssertEqual(textfield.text, "61 2345678")
		textfield.set(phoneNumber: "+96412345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+964")
		XCTAssertEqual(textfield.selectedCountry?.code, "IQ")
		XCTAssertEqual(textfield.text, "1 234 5678")
		textfield.set(phoneNumber: "+982123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+98")
		XCTAssertEqual(textfield.selectedCountry?.code, "IR")
		XCTAssertEqual(textfield.text, "21 2345 6789")
		textfield.set(phoneNumber: "+3532212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+353")
		XCTAssertEqual(textfield.selectedCountry?.code, "IE")
		XCTAssertEqual(textfield.text, "22 12345")
		textfield.set(phoneNumber: "+3544101234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+354")
		XCTAssertEqual(textfield.selectedCountry?.code, "IS")
		XCTAssertEqual(textfield.text, "410 1234")
		textfield.set(phoneNumber: "+97221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+972")
		XCTAssertEqual(textfield.selectedCountry?.code, "IL")
		XCTAssertEqual(textfield.text, "2-123-4567")
		textfield.set(phoneNumber: "+39054988")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+39")
		XCTAssertEqual(textfield.selectedCountry?.code, "IT")
		XCTAssertEqual(textfield.text, "54988")
		textfield.set(phoneNumber: "+61891641234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+61")
		XCTAssertEqual(textfield.selectedCountry?.code, "CX")
		XCTAssertEqual(textfield.text, "8 9164 1234")
		textfield.set(phoneNumber: "+672106609")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+672")
		XCTAssertEqual(textfield.selectedCountry?.code, "NF")
		XCTAssertEqual(textfield.text, "10 6609")
		textfield.set(phoneNumber: "+441624756789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+44")
		XCTAssertEqual(textfield.selectedCountry?.code, "IM")
		XCTAssertEqual(textfield.text, "1624 756789")
		textfield.set(phoneNumber: "+358181234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+358")
		XCTAssertEqual(textfield.selectedCountry?.code, "AX")
		XCTAssertEqual(textfield.text, "18 1234567")
		textfield.set(phoneNumber: "+13452221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "KY")
		XCTAssertEqual(textfield.text, "345-222-1234")
		textfield.set(phoneNumber: "+61891621234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+61")
		XCTAssertEqual(textfield.selectedCountry?.code, "CC")
		XCTAssertEqual(textfield.text, "8 9162 1234")
		textfield.set(phoneNumber: "+68221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+682")
		XCTAssertEqual(textfield.selectedCountry?.code, "CK")
		XCTAssertEqual(textfield.text, "21 234")
		textfield.set(phoneNumber: "+298201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+298")
		XCTAssertEqual(textfield.selectedCountry?.code, "FO")
		XCTAssertEqual(textfield.text, "201234")
		textfield.set(phoneNumber: "+50031234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+500")
		XCTAssertEqual(textfield.selectedCountry?.code, "FK")
		XCTAssertEqual(textfield.text, "31234")
		textfield.set(phoneNumber: "+16702345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "MP")
		XCTAssertEqual(textfield.text, "670-234-5678")
		textfield.set(phoneNumber: "+6922471234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+692")
		XCTAssertEqual(textfield.selectedCountry?.code, "MH")
		XCTAssertEqual(textfield.text, "247-1234")
		textfield.set(phoneNumber: "+67740123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+677")
		XCTAssertEqual(textfield.selectedCountry?.code, "SB")
		XCTAssertEqual(textfield.text, "40123")
		textfield.set(phoneNumber: "+16497121234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "TC")
		XCTAssertEqual(textfield.text, "649-712-1234")
		textfield.set(phoneNumber: "+12842291234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "VG")
		XCTAssertEqual(textfield.text, "284-229-1234")
		textfield.set(phoneNumber: "+13406421234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "VI")
		XCTAssertEqual(textfield.text, "340-642-1234")
		textfield.set(phoneNumber: "+18765123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "JM")
		XCTAssertEqual(textfield.text, "876-512-3456")
		textfield.set(phoneNumber: "+81312345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+81")
		XCTAssertEqual(textfield.selectedCountry?.code, "JP")
		XCTAssertEqual(textfield.text, "3-1234-5678")
		textfield.set(phoneNumber: "+441534456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+44")
		XCTAssertEqual(textfield.selectedCountry?.code, "JE")
		XCTAssertEqual(textfield.text, "1534 456789")
		textfield.set(phoneNumber: "+96262001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+962")
		XCTAssertEqual(textfield.selectedCountry?.code, "JO")
		XCTAssertEqual(textfield.text, "6 200 1234")
		textfield.set(phoneNumber: "+77123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+7")
		XCTAssertEqual(textfield.selectedCountry?.code, "KZ")
		XCTAssertEqual(textfield.text, "712 345 6789")
		textfield.set(phoneNumber: "+254202012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+254")
		XCTAssertEqual(textfield.selectedCountry?.code, "KE")
		XCTAssertEqual(textfield.text, "20 2012345")
		textfield.set(phoneNumber: "+996312123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+996")
		XCTAssertEqual(textfield.selectedCountry?.code, "KG")
		XCTAssertEqual(textfield.text, "312 123 456")
		textfield.set(phoneNumber: "+68631234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+686")
		XCTAssertEqual(textfield.selectedCountry?.code, "KI")
		XCTAssertEqual(textfield.text, "31234")
		textfield.set(phoneNumber: "+96522345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+965")
		XCTAssertEqual(textfield.selectedCountry?.code, "KW")
		XCTAssertEqual(textfield.text, "2234 5678")
		textfield.set(phoneNumber: "+262262161234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+262")
		XCTAssertEqual(textfield.selectedCountry?.code, "RE")
		XCTAssertEqual(textfield.text, "262 16 12 34")
		textfield.set(phoneNumber: "+85621212862")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+856")
		XCTAssertEqual(textfield.selectedCountry?.code, "LA")
		XCTAssertEqual(textfield.text, "21 212 862")
		textfield.set(phoneNumber: "+26622123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+266")
		XCTAssertEqual(textfield.selectedCountry?.code, "LS")
		XCTAssertEqual(textfield.text, "2212 3456")
		textfield.set(phoneNumber: "+37163123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+371")
		XCTAssertEqual(textfield.selectedCountry?.code, "LV")
		XCTAssertEqual(textfield.text, "63 123 456")
		textfield.set(phoneNumber: "+9611123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+961")
		XCTAssertEqual(textfield.selectedCountry?.code, "LB")
		XCTAssertEqual(textfield.text, "1 123 456")
		textfield.set(phoneNumber: "+23121234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+231")
		XCTAssertEqual(textfield.selectedCountry?.code, "LR")
		XCTAssertEqual(textfield.text, "21 234 567")
		textfield.set(phoneNumber: "+218212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+218")
		XCTAssertEqual(textfield.selectedCountry?.code, "LY")
		XCTAssertEqual(textfield.text, "21-2345678")
		textfield.set(phoneNumber: "+4232345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+423")
		XCTAssertEqual(textfield.selectedCountry?.code, "LI")
		XCTAssertEqual(textfield.text, "234 56 78")
		textfield.set(phoneNumber: "+37031234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+370")
		XCTAssertEqual(textfield.selectedCountry?.code, "LT")
		XCTAssertEqual(textfield.text, "312 34567")
		textfield.set(phoneNumber: "+35227123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+352")
		XCTAssertEqual(textfield.selectedCountry?.code, "LU")
		XCTAssertEqual(textfield.text, "27 12 34 56")
		textfield.set(phoneNumber: "+85328212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+853")
		XCTAssertEqual(textfield.selectedCountry?.code, "MO")
		XCTAssertEqual(textfield.text, "2821 2345")
		textfield.set(phoneNumber: "+38922212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+389")
		XCTAssertEqual(textfield.selectedCountry?.code, "MK")
		XCTAssertEqual(textfield.text, "2 221 2345")
		textfield.set(phoneNumber: "+261202123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+261")
		XCTAssertEqual(textfield.selectedCountry?.code, "MG")
		XCTAssertEqual(textfield.text, "20 21 234 56")
		textfield.set(phoneNumber: "+60323856789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+60")
		XCTAssertEqual(textfield.selectedCountry?.code, "MY")
		XCTAssertEqual(textfield.text, "3-2385 6789")
		textfield.set(phoneNumber: "+2651234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+265")
		XCTAssertEqual(textfield.selectedCountry?.code, "MW")
		XCTAssertEqual(textfield.text, "1 234 567")
		textfield.set(phoneNumber: "+9606701234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+960")
		XCTAssertEqual(textfield.selectedCountry?.code, "MV")
		XCTAssertEqual(textfield.text, "670-1234")
		textfield.set(phoneNumber: "+22320212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+223")
		XCTAssertEqual(textfield.selectedCountry?.code, "ML")
		XCTAssertEqual(textfield.text, "20 21 23 45")
		textfield.set(phoneNumber: "+35621001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+356")
		XCTAssertEqual(textfield.selectedCountry?.code, "MT")
		XCTAssertEqual(textfield.text, "2100 1234")
		textfield.set(phoneNumber: "+212520123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+212")
		XCTAssertEqual(textfield.selectedCountry?.code, "MA")
		XCTAssertEqual(textfield.text, "520-123456")
		textfield.set(phoneNumber: "+596596301234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+596")
		XCTAssertEqual(textfield.selectedCountry?.code, "MQ")
		XCTAssertEqual(textfield.text, "596 30 12 34")
		textfield.set(phoneNumber: "+2302012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+230")
		XCTAssertEqual(textfield.selectedCountry?.code, "MU")
		XCTAssertEqual(textfield.text, "201 2345")
		textfield.set(phoneNumber: "+22235123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+222")
		XCTAssertEqual(textfield.selectedCountry?.code, "MR")
		XCTAssertEqual(textfield.text, "35 12 34 56")
		textfield.set(phoneNumber: "+262269601234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+262")
		XCTAssertEqual(textfield.selectedCountry?.code, "YT")
		XCTAssertEqual(textfield.text, "269 60 12 34")
		textfield.set(phoneNumber: "+522221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+52")
		XCTAssertEqual(textfield.selectedCountry?.code, "MX")
		XCTAssertEqual(textfield.text, "222 123 4567")
		textfield.set(phoneNumber: "+37322212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+373")
		XCTAssertEqual(textfield.selectedCountry?.code, "MD")
		XCTAssertEqual(textfield.text, "22 212 345")
		textfield.set(phoneNumber: "+37799123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+377")
		XCTAssertEqual(textfield.selectedCountry?.code, "MC")
		XCTAssertEqual(textfield.text, "99 12 34 56")
		textfield.set(phoneNumber: "+97650123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+976")
		XCTAssertEqual(textfield.selectedCountry?.code, "MN")
		XCTAssertEqual(textfield.text, "5012 3456")
		textfield.set(phoneNumber: "+38230234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+382")
		XCTAssertEqual(textfield.selectedCountry?.code, "ME")
		XCTAssertEqual(textfield.text, "30 234 567")
		textfield.set(phoneNumber: "+16644912345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "MS")
		XCTAssertEqual(textfield.text, "664-491-2345")
		textfield.set(phoneNumber: "+25821123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+258")
		XCTAssertEqual(textfield.selectedCountry?.code, "MZ")
		XCTAssertEqual(textfield.text, "21 123 456")
		textfield.set(phoneNumber: "+951234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+95")
		XCTAssertEqual(textfield.selectedCountry?.code, "MM")
		XCTAssertEqual(textfield.text, "1 234 567")
		textfield.set(phoneNumber: "+26461221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+264")
		XCTAssertEqual(textfield.selectedCountry?.code, "NA")
		XCTAssertEqual(textfield.text, "61 221 234")
		textfield.set(phoneNumber: "+6744441234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+674")
		XCTAssertEqual(textfield.selectedCountry?.code, "NR")
		XCTAssertEqual(textfield.text, "444 1234")
		textfield.set(phoneNumber: "+97714567890")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+977")
		XCTAssertEqual(textfield.selectedCountry?.code, "NP")
		XCTAssertEqual(textfield.text, "1-4567890")
		textfield.set(phoneNumber: "+50521234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+505")
		XCTAssertEqual(textfield.selectedCountry?.code, "NI")
		XCTAssertEqual(textfield.text, "2123 4567")
		textfield.set(phoneNumber: "+22720201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+227")
		XCTAssertEqual(textfield.selectedCountry?.code, "NE")
		XCTAssertEqual(textfield.text, "20 20 12 34")
		textfield.set(phoneNumber: "+23412345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+234")
		XCTAssertEqual(textfield.selectedCountry?.code, "NG")
		XCTAssertEqual(textfield.text, "1 234 5678")
		textfield.set(phoneNumber: "+6834002")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+683")
		XCTAssertEqual(textfield.selectedCountry?.code, "NU")
		XCTAssertEqual(textfield.text, "4002")
		textfield.set(phoneNumber: "+4721234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+47")
		XCTAssertEqual(textfield.selectedCountry?.code, "NO")
		XCTAssertEqual(textfield.text, "21 23 45 67")
		textfield.set(phoneNumber: "+687201234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+687")
		XCTAssertEqual(textfield.selectedCountry?.code, "NC")
		XCTAssertEqual(textfield.text, "20.12.34")
		textfield.set(phoneNumber: "+6432345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+64")
		XCTAssertEqual(textfield.selectedCountry?.code, "NZ")
		XCTAssertEqual(textfield.text, "3-234 5678")
		textfield.set(phoneNumber: "+96823123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+968")
		XCTAssertEqual(textfield.selectedCountry?.code, "OM")
		XCTAssertEqual(textfield.text, "23 123456")
		textfield.set(phoneNumber: "+256312345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+256")
		XCTAssertEqual(textfield.selectedCountry?.code, "UG")
		XCTAssertEqual(textfield.text, "31 2345678")
		textfield.set(phoneNumber: "+998662345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+998")
		XCTAssertEqual(textfield.selectedCountry?.code, "UZ")
		XCTAssertEqual(textfield.text, "66 234 56 78")
		textfield.set(phoneNumber: "+922123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+92")
		XCTAssertEqual(textfield.selectedCountry?.code, "PK")
		XCTAssertEqual(textfield.text, "21 23456789")
		textfield.set(phoneNumber: "+6802771234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+680")
		XCTAssertEqual(textfield.selectedCountry?.code, "PW")
		XCTAssertEqual(textfield.text, "277 1234")
		textfield.set(phoneNumber: "+5072001234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+507")
		XCTAssertEqual(textfield.selectedCountry?.code, "PA")
		XCTAssertEqual(textfield.text, "200-1234")
		textfield.set(phoneNumber: "+6753123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+675")
		XCTAssertEqual(textfield.selectedCountry?.code, "PG")
		XCTAssertEqual(textfield.text, "312 3456")
		textfield.set(phoneNumber: "+595212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+595")
		XCTAssertEqual(textfield.selectedCountry?.code, "PY")
		XCTAssertEqual(textfield.text, "21 234 5678")
		textfield.set(phoneNumber: "+31101234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+31")
		XCTAssertEqual(textfield.selectedCountry?.code, "NL")
		XCTAssertEqual(textfield.text, "10 123 4567")
		textfield.set(phoneNumber: "+5111234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+51")
		XCTAssertEqual(textfield.selectedCountry?.code, "PE")
		XCTAssertEqual(textfield.text, "1 1234567")
		textfield.set(phoneNumber: "+6321234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+63")
		XCTAssertEqual(textfield.selectedCountry?.code, "PH")
		XCTAssertEqual(textfield.text, "2 123 4567")
		textfield.set(phoneNumber: "+48123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+48")
		XCTAssertEqual(textfield.selectedCountry?.code, "PL")
		XCTAssertEqual(textfield.text, "12 345 67 89")
		textfield.set(phoneNumber: "+68940412345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+689")
		XCTAssertEqual(textfield.selectedCountry?.code, "PF")
		XCTAssertEqual(textfield.text, "40 41 23 45")
		textfield.set(phoneNumber: "+17872345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "PR")
		XCTAssertEqual(textfield.text, "787-234-5678")
		textfield.set(phoneNumber: "+351212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+351")
		XCTAssertEqual(textfield.selectedCountry?.code, "PT")
		XCTAssertEqual(textfield.text, "21 234 5678")
		textfield.set(phoneNumber: "+97444123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+974")
		XCTAssertEqual(textfield.selectedCountry?.code, "QA")
		XCTAssertEqual(textfield.text, "4412 3456")
		textfield.set(phoneNumber: "+23621612345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+236")
		XCTAssertEqual(textfield.selectedCountry?.code, "CF")
		XCTAssertEqual(textfield.text, "21 61 23 45")
		textfield.set(phoneNumber: "+18092345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "DO")
		XCTAssertEqual(textfield.text, "809-234-5678")
		textfield.set(phoneNumber: "+40211234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+40")
		XCTAssertEqual(textfield.selectedCountry?.code, "RO")
		XCTAssertEqual(textfield.text, "21 123 4567")
		textfield.set(phoneNumber: "+441212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+44")
		XCTAssertEqual(textfield.selectedCountry?.code, "GB")
		XCTAssertEqual(textfield.text, "121 234 5678")
		textfield.set(phoneNumber: "+73011234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+7")
		XCTAssertEqual(textfield.selectedCountry?.code, "RU")
		XCTAssertEqual(textfield.text, "301 123-45-67")
		textfield.set(phoneNumber: "+250250123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+250")
		XCTAssertEqual(textfield.selectedCountry?.code, "RW")
		XCTAssertEqual(textfield.text, "250 123 456")
		textfield.set(phoneNumber: "+590590271234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+590")
		XCTAssertEqual(textfield.selectedCountry?.code, "BL")
		XCTAssertEqual(textfield.text, "590 27-1234")
		textfield.set(phoneNumber: "+18692361234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "KN")
		XCTAssertEqual(textfield.text, "869-236-1234")
		textfield.set(phoneNumber: "+3780549876811")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+378")
		XCTAssertEqual(textfield.selectedCountry?.code, "SM")
		XCTAssertEqual(textfield.text, "549876811")
		//		textfield.set(phoneNumber: "+590590271234")
		//		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+590")
		//		XCTAssertEqual(textfield.selectedCountry?.code, "MF")
		//		XCTAssertEqual(textfield.text, "590 27-1234")
		textfield.set(phoneNumber: "+508411234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+508")
		XCTAssertEqual(textfield.selectedCountry?.code, "PM")
		XCTAssertEqual(textfield.text, "41 12 34")
		textfield.set(phoneNumber: "+17842661234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "VC")
		XCTAssertEqual(textfield.text, "784-266-1234")
		textfield.set(phoneNumber: "+29022158")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+290")
		XCTAssertEqual(textfield.selectedCountry?.code, "SH")
		XCTAssertEqual(textfield.text, "22158")
		textfield.set(phoneNumber: "+17584305678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "LC")
		XCTAssertEqual(textfield.text, "758-430-5678")
		textfield.set(phoneNumber: "+68522123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+685")
		XCTAssertEqual(textfield.selectedCountry?.code, "WS")
		XCTAssertEqual(textfield.text, "22123")
		textfield.set(phoneNumber: "+16846221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "AS")
		XCTAssertEqual(textfield.text, "684-622-1234")
		textfield.set(phoneNumber: "+2392221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+239")
		XCTAssertEqual(textfield.selectedCountry?.code, "ST")
		XCTAssertEqual(textfield.text, "222 1234")
		textfield.set(phoneNumber: "+38110234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+381")
		XCTAssertEqual(textfield.selectedCountry?.code, "RS")
		XCTAssertEqual(textfield.text, "10 234567")
		textfield.set(phoneNumber: "+2484217123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+248")
		XCTAssertEqual(textfield.selectedCountry?.code, "SC")
		XCTAssertEqual(textfield.text, "4 217 123")
		textfield.set(phoneNumber: "+221301012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+221")
		XCTAssertEqual(textfield.selectedCountry?.code, "SN")
		XCTAssertEqual(textfield.text, "30 101 23 45")
		textfield.set(phoneNumber: "+23222221234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+232")
		XCTAssertEqual(textfield.selectedCountry?.code, "SL")
		XCTAssertEqual(textfield.text, "22 221234")
		textfield.set(phoneNumber: "+6561234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+65")
		XCTAssertEqual(textfield.selectedCountry?.code, "SG")
		XCTAssertEqual(textfield.text, "6123 4567")
		textfield.set(phoneNumber: "+421221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+421")
		XCTAssertEqual(textfield.selectedCountry?.code, "SK")
		XCTAssertEqual(textfield.text, "2/212 345 67")
		textfield.set(phoneNumber: "+38611234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+386")
		XCTAssertEqual(textfield.selectedCountry?.code, "SI")
		XCTAssertEqual(textfield.text, "1 123 45 67")
		textfield.set(phoneNumber: "+2524012345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+252")
		XCTAssertEqual(textfield.selectedCountry?.code, "SO")
		XCTAssertEqual(textfield.text, "4 012345")
		textfield.set(phoneNumber: "+249121231234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+249")
		XCTAssertEqual(textfield.selectedCountry?.code, "SD")
		XCTAssertEqual(textfield.text, "12 123 1234")
		textfield.set(phoneNumber: "+211181234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+211")
		XCTAssertEqual(textfield.selectedCountry?.code, "SS")
		XCTAssertEqual(textfield.text, "181 234 567")
		textfield.set(phoneNumber: "+94112345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+94")
		XCTAssertEqual(textfield.selectedCountry?.code, "LK")
		XCTAssertEqual(textfield.text, "112 345 678")
		textfield.set(phoneNumber: "+468123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+46")
		XCTAssertEqual(textfield.selectedCountry?.code, "SE")
		XCTAssertEqual(textfield.text, "8 12 34 56")
		textfield.set(phoneNumber: "+41212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+41")
		XCTAssertEqual(textfield.selectedCountry?.code, "CH")
		XCTAssertEqual(textfield.text, "21 234 56 78")
		textfield.set(phoneNumber: "+597211234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+597")
		XCTAssertEqual(textfield.selectedCountry?.code, "SR")
		XCTAssertEqual(textfield.text, "211-234")
		textfield.set(phoneNumber: "+4779123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+47")
		XCTAssertEqual(textfield.selectedCountry?.code, "SJ")
		XCTAssertEqual(textfield.text, "79 12 34 56")
		textfield.set(phoneNumber: "+26822171234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+268")
		XCTAssertEqual(textfield.selectedCountry?.code, "SZ")
		XCTAssertEqual(textfield.text, "2217 1234")
		textfield.set(phoneNumber: "+963112345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+963")
		XCTAssertEqual(textfield.selectedCountry?.code, "SY")
		XCTAssertEqual(textfield.text, "11 234 5678")
		textfield.set(phoneNumber: "+992372123456")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+992")
		XCTAssertEqual(textfield.selectedCountry?.code, "TJ")
		XCTAssertEqual(textfield.text, "372 12 3456")
		textfield.set(phoneNumber: "+886221234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+886")
		XCTAssertEqual(textfield.selectedCountry?.code, "TW")
		XCTAssertEqual(textfield.text, "2 2123 4567")
		textfield.set(phoneNumber: "+255222345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+255")
		XCTAssertEqual(textfield.selectedCountry?.code, "TZ")
		XCTAssertEqual(textfield.text, "22 234 5678")
		textfield.set(phoneNumber: "+23522501234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+235")
		XCTAssertEqual(textfield.selectedCountry?.code, "TD")
		XCTAssertEqual(textfield.text, "22 50 12 34")
		textfield.set(phoneNumber: "+420212345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+420")
		XCTAssertEqual(textfield.selectedCountry?.code, "CZ")
		XCTAssertEqual(textfield.text, "212 345 678")
		textfield.set(phoneNumber: "+2463709100")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+246")
		XCTAssertEqual(textfield.selectedCountry?.code, "IO")
		XCTAssertEqual(textfield.text, "370 9100")
		textfield.set(phoneNumber: "+97022234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+970")
		XCTAssertEqual(textfield.selectedCountry?.code, "PS")
		XCTAssertEqual(textfield.text, "2 223 4567")
		textfield.set(phoneNumber: "+6621234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+66")
		XCTAssertEqual(textfield.selectedCountry?.code, "TH")
		XCTAssertEqual(textfield.text, "2 123 4567")
		textfield.set(phoneNumber: "+6702112345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+670")
		XCTAssertEqual(textfield.selectedCountry?.code, "TL")
		XCTAssertEqual(textfield.text, "211 2345")
		textfield.set(phoneNumber: "+22822212345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+228")
		XCTAssertEqual(textfield.selectedCountry?.code, "TG")
		XCTAssertEqual(textfield.text, "22 21 23 45")
		textfield.set(phoneNumber: "+6903101")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+690")
		XCTAssertEqual(textfield.selectedCountry?.code, "TK")
		XCTAssertEqual(textfield.text, "3101")
		textfield.set(phoneNumber: "+67620123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+676")
		XCTAssertEqual(textfield.selectedCountry?.code, "TO")
		XCTAssertEqual(textfield.text, "20-123")
		textfield.set(phoneNumber: "+18682211234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+1")
		XCTAssertEqual(textfield.selectedCountry?.code, "TT")
		XCTAssertEqual(textfield.text, "868-221-1234")
		textfield.set(phoneNumber: "+21671234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+216")
		XCTAssertEqual(textfield.selectedCountry?.code, "TN")
		XCTAssertEqual(textfield.text, "71 234 567")
		textfield.set(phoneNumber: "+99312345678")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+993")
		XCTAssertEqual(textfield.selectedCountry?.code, "TM")
		XCTAssertEqual(textfield.text, "12 34-56-78")
		textfield.set(phoneNumber: "+902123456789")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+90")
		XCTAssertEqual(textfield.selectedCountry?.code, "TR")
		XCTAssertEqual(textfield.text, "212 345 67 89")
		textfield.set(phoneNumber: "+68820123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+688")
		XCTAssertEqual(textfield.selectedCountry?.code, "TV")
		XCTAssertEqual(textfield.text, "20123")
		textfield.set(phoneNumber: "+380311234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+380")
		XCTAssertEqual(textfield.selectedCountry?.code, "UA")
		XCTAssertEqual(textfield.text, "3112 34567")
		textfield.set(phoneNumber: "+59821231234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+598")
		XCTAssertEqual(textfield.selectedCountry?.code, "UY")
		XCTAssertEqual(textfield.text, "2123 1234")
		textfield.set(phoneNumber: "+67822123")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+678")
		XCTAssertEqual(textfield.selectedCountry?.code, "VU")
		XCTAssertEqual(textfield.text, "22123")
		textfield.set(phoneNumber: "+582121234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+58")
		XCTAssertEqual(textfield.selectedCountry?.code, "VE")
		XCTAssertEqual(textfield.text, "212-1234567")
		textfield.set(phoneNumber: "+842101234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+84")
		XCTAssertEqual(textfield.selectedCountry?.code, "VN")
		XCTAssertEqual(textfield.text, "210 1234 567")
		textfield.set(phoneNumber: "+681501234")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+681")
		XCTAssertEqual(textfield.selectedCountry?.code, "WF")
		XCTAssertEqual(textfield.text, "50 12 34")
		textfield.set(phoneNumber: "+9671234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+967")
		XCTAssertEqual(textfield.selectedCountry?.code, "YE")
		XCTAssertEqual(textfield.text, "1 234 567")
		textfield.set(phoneNumber: "+260211234567")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+260")
		XCTAssertEqual(textfield.selectedCountry?.code, "ZM")
		XCTAssertEqual(textfield.text, "21 1234567")
		textfield.set(phoneNumber: "+2631312345")
		XCTAssertEqual(textfield.selectedCountry?.phoneCode, "+263")
		XCTAssertEqual(textfield.selectedCountry?.code, "ZW")
		XCTAssertEqual(textfield.text, "13 12345")
	}

	func testSetFlag() {
		textfield.setFlag(for: "AF")
		XCTAssertEqual(textfield.selectedCountry?.code, "AF")
		textfield.setFlag(for: "AL")
		XCTAssertEqual(textfield.selectedCountry?.code, "AL")
		textfield.setFlag(for: "DZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "DZ")
		textfield.setFlag(for: "AS")
		XCTAssertEqual(textfield.selectedCountry?.code, "AS")
		textfield.setFlag(for: "AD")
		XCTAssertEqual(textfield.selectedCountry?.code, "AD")
		textfield.setFlag(for: "AO")
		XCTAssertEqual(textfield.selectedCountry?.code, "AO")
		textfield.setFlag(for: "AI")
		XCTAssertEqual(textfield.selectedCountry?.code, "AI")
		textfield.setFlag(for: "AG")
		XCTAssertEqual(textfield.selectedCountry?.code, "AG")
		textfield.setFlag(for: "AR")
		XCTAssertEqual(textfield.selectedCountry?.code, "AR")
		textfield.setFlag(for: "AM")
		XCTAssertEqual(textfield.selectedCountry?.code, "AM")
		textfield.setFlag(for: "AW")
		XCTAssertEqual(textfield.selectedCountry?.code, "AW")
		textfield.setFlag(for: "AU")
		XCTAssertEqual(textfield.selectedCountry?.code, "AU")
		textfield.setFlag(for: "AT")
		XCTAssertEqual(textfield.selectedCountry?.code, "AT")
		textfield.setFlag(for: "AZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "AZ")
		textfield.setFlag(for: "AX")
		XCTAssertEqual(textfield.selectedCountry?.code, "AX")
		textfield.setFlag(for: "BS")
		XCTAssertEqual(textfield.selectedCountry?.code, "BS")
		textfield.setFlag(for: "BH")
		XCTAssertEqual(textfield.selectedCountry?.code, "BH")
		textfield.setFlag(for: "BD")
		XCTAssertEqual(textfield.selectedCountry?.code, "BD")
		textfield.setFlag(for: "BB")
		XCTAssertEqual(textfield.selectedCountry?.code, "BB")
		textfield.setFlag(for: "BY")
		XCTAssertEqual(textfield.selectedCountry?.code, "BY")
		textfield.setFlag(for: "BE")
		XCTAssertEqual(textfield.selectedCountry?.code, "BE")
		textfield.setFlag(for: "BZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "BZ")
		textfield.setFlag(for: "BJ")
		XCTAssertEqual(textfield.selectedCountry?.code, "BJ")
		textfield.setFlag(for: "BM")
		XCTAssertEqual(textfield.selectedCountry?.code, "BM")
		textfield.setFlag(for: "BT")
		XCTAssertEqual(textfield.selectedCountry?.code, "BT")
		textfield.setFlag(for: "BO")
		XCTAssertEqual(textfield.selectedCountry?.code, "BO")
		textfield.setFlag(for: "BA")
		XCTAssertEqual(textfield.selectedCountry?.code, "BA")
		textfield.setFlag(for: "BW")
		XCTAssertEqual(textfield.selectedCountry?.code, "BW")
		textfield.setFlag(for: "BR")
		XCTAssertEqual(textfield.selectedCountry?.code, "BR")
		textfield.setFlag(for: "IO")
		XCTAssertEqual(textfield.selectedCountry?.code, "IO")
		textfield.setFlag(for: "VG")
		XCTAssertEqual(textfield.selectedCountry?.code, "VG")
		textfield.setFlag(for: "BN")
		XCTAssertEqual(textfield.selectedCountry?.code, "BN")
		textfield.setFlag(for: "BG")
		XCTAssertEqual(textfield.selectedCountry?.code, "BG")
		textfield.setFlag(for: "BF")
		XCTAssertEqual(textfield.selectedCountry?.code, "BF")
		textfield.setFlag(for: "BI")
		XCTAssertEqual(textfield.selectedCountry?.code, "BI")
		textfield.setFlag(for: "KH")
		XCTAssertEqual(textfield.selectedCountry?.code, "KH")
		textfield.setFlag(for: "CM")
		XCTAssertEqual(textfield.selectedCountry?.code, "CM")
		textfield.setFlag(for: "CA")
		XCTAssertEqual(textfield.selectedCountry?.code, "CA")
		textfield.setFlag(for: "CV")
		XCTAssertEqual(textfield.selectedCountry?.code, "CV")
		textfield.setFlag(for: "KY")
		XCTAssertEqual(textfield.selectedCountry?.code, "KY")
		textfield.setFlag(for: "CF")
		XCTAssertEqual(textfield.selectedCountry?.code, "CF")
		textfield.setFlag(for: "TD")
		XCTAssertEqual(textfield.selectedCountry?.code, "TD")
		textfield.setFlag(for: "CL")
		XCTAssertEqual(textfield.selectedCountry?.code, "CL")
		textfield.setFlag(for: "CN")
		XCTAssertEqual(textfield.selectedCountry?.code, "CN")
		textfield.setFlag(for: "CX")
		XCTAssertEqual(textfield.selectedCountry?.code, "CX")
		textfield.setFlag(for: "CC")
		XCTAssertEqual(textfield.selectedCountry?.code, "CC")
		textfield.setFlag(for: "CO")
		XCTAssertEqual(textfield.selectedCountry?.code, "CO")
		textfield.setFlag(for: "KM")
		XCTAssertEqual(textfield.selectedCountry?.code, "KM")
		textfield.setFlag(for: "CG")
		XCTAssertEqual(textfield.selectedCountry?.code, "CG")
		textfield.setFlag(for: "CD")
		XCTAssertEqual(textfield.selectedCountry?.code, "CD")
		textfield.setFlag(for: "CK")
		XCTAssertEqual(textfield.selectedCountry?.code, "CK")
		textfield.setFlag(for: "CR")
		XCTAssertEqual(textfield.selectedCountry?.code, "CR")
		textfield.setFlag(for: "CI")
		XCTAssertEqual(textfield.selectedCountry?.code, "CI")
		textfield.setFlag(for: "HR")
		XCTAssertEqual(textfield.selectedCountry?.code, "HR")
		textfield.setFlag(for: "CU")
		XCTAssertEqual(textfield.selectedCountry?.code, "CU")
		textfield.setFlag(for: "CY")
		XCTAssertEqual(textfield.selectedCountry?.code, "CY")
		textfield.setFlag(for: "CZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "CZ")
		textfield.setFlag(for: "DK")
		XCTAssertEqual(textfield.selectedCountry?.code, "DK")
		textfield.setFlag(for: "DJ")
		XCTAssertEqual(textfield.selectedCountry?.code, "DJ")
		textfield.setFlag(for: "DM")
		XCTAssertEqual(textfield.selectedCountry?.code, "DM")
		textfield.setFlag(for: "DO")
		XCTAssertEqual(textfield.selectedCountry?.code, "DO")
		textfield.setFlag(for: "EC")
		XCTAssertEqual(textfield.selectedCountry?.code, "EC")
		textfield.setFlag(for: "EG")
		XCTAssertEqual(textfield.selectedCountry?.code, "EG")
		textfield.setFlag(for: "SV")
		XCTAssertEqual(textfield.selectedCountry?.code, "SV")
		textfield.setFlag(for: "GQ")
		XCTAssertEqual(textfield.selectedCountry?.code, "GQ")
		textfield.setFlag(for: "ER")
		XCTAssertEqual(textfield.selectedCountry?.code, "ER")
		textfield.setFlag(for: "EE")
		XCTAssertEqual(textfield.selectedCountry?.code, "EE")
		textfield.setFlag(for: "ET")
		XCTAssertEqual(textfield.selectedCountry?.code, "ET")
		textfield.setFlag(for: "FK")
		XCTAssertEqual(textfield.selectedCountry?.code, "FK")
		textfield.setFlag(for: "FO")
		XCTAssertEqual(textfield.selectedCountry?.code, "FO")
		textfield.setFlag(for: "FJ")
		XCTAssertEqual(textfield.selectedCountry?.code, "FJ")
		textfield.setFlag(for: "FI")
		XCTAssertEqual(textfield.selectedCountry?.code, "FI")
		textfield.setFlag(for: "FR")
		XCTAssertEqual(textfield.selectedCountry?.code, "FR")
		textfield.setFlag(for: "GF")
		XCTAssertEqual(textfield.selectedCountry?.code, "GF")
		textfield.setFlag(for: "PF")
		XCTAssertEqual(textfield.selectedCountry?.code, "PF")
		textfield.setFlag(for: "GA")
		XCTAssertEqual(textfield.selectedCountry?.code, "GA")
		textfield.setFlag(for: "GM")
		XCTAssertEqual(textfield.selectedCountry?.code, "GM")
		textfield.setFlag(for: "GE")
		XCTAssertEqual(textfield.selectedCountry?.code, "GE")
		textfield.setFlag(for: "DE")
		XCTAssertEqual(textfield.selectedCountry?.code, "DE")
		textfield.setFlag(for: "GH")
		XCTAssertEqual(textfield.selectedCountry?.code, "GH")
		textfield.setFlag(for: "GI")
		XCTAssertEqual(textfield.selectedCountry?.code, "GI")
		textfield.setFlag(for: "GR")
		XCTAssertEqual(textfield.selectedCountry?.code, "GR")
		textfield.setFlag(for: "GL")
		XCTAssertEqual(textfield.selectedCountry?.code, "GL")
		textfield.setFlag(for: "GD")
		XCTAssertEqual(textfield.selectedCountry?.code, "GD")
		textfield.setFlag(for: "GP")
		XCTAssertEqual(textfield.selectedCountry?.code, "GP")
		textfield.setFlag(for: "GU")
		XCTAssertEqual(textfield.selectedCountry?.code, "GU")
		textfield.setFlag(for: "GT")
		XCTAssertEqual(textfield.selectedCountry?.code, "GT")
		textfield.setFlag(for: "GG")
		XCTAssertEqual(textfield.selectedCountry?.code, "GG")
		textfield.setFlag(for: "GN")
		XCTAssertEqual(textfield.selectedCountry?.code, "GN")
		textfield.setFlag(for: "GW")
		XCTAssertEqual(textfield.selectedCountry?.code, "GW")
		textfield.setFlag(for: "GY")
		XCTAssertEqual(textfield.selectedCountry?.code, "GY")
		textfield.setFlag(for: "HT")
		XCTAssertEqual(textfield.selectedCountry?.code, "HT")
		textfield.setFlag(for: "HN")
		XCTAssertEqual(textfield.selectedCountry?.code, "HN")
		textfield.setFlag(for: "HK")
		XCTAssertEqual(textfield.selectedCountry?.code, "HK")
		textfield.setFlag(for: "HU")
		XCTAssertEqual(textfield.selectedCountry?.code, "HU")
		textfield.setFlag(for: "IS")
		XCTAssertEqual(textfield.selectedCountry?.code, "IS")
		textfield.setFlag(for: "IN")
		XCTAssertEqual(textfield.selectedCountry?.code, "IN")
		textfield.setFlag(for: "ID")
		XCTAssertEqual(textfield.selectedCountry?.code, "ID")
		textfield.setFlag(for: "IR")
		XCTAssertEqual(textfield.selectedCountry?.code, "IR")
		textfield.setFlag(for: "IQ")
		XCTAssertEqual(textfield.selectedCountry?.code, "IQ")
		textfield.setFlag(for: "IE")
		XCTAssertEqual(textfield.selectedCountry?.code, "IE")
		textfield.setFlag(for: "IM")
		XCTAssertEqual(textfield.selectedCountry?.code, "IM")
		textfield.setFlag(for: "IL")
		XCTAssertEqual(textfield.selectedCountry?.code, "IL")
		textfield.setFlag(for: "IT")
		XCTAssertEqual(textfield.selectedCountry?.code, "IT")
		textfield.setFlag(for: "JM")
		XCTAssertEqual(textfield.selectedCountry?.code, "JM")
		textfield.setFlag(for: "JP")
		XCTAssertEqual(textfield.selectedCountry?.code, "JP")
		textfield.setFlag(for: "JE")
		XCTAssertEqual(textfield.selectedCountry?.code, "JE")
		textfield.setFlag(for: "JO")
		XCTAssertEqual(textfield.selectedCountry?.code, "JO")
		textfield.setFlag(for: "KZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "KZ")
		textfield.setFlag(for: "KE")
		XCTAssertEqual(textfield.selectedCountry?.code, "KE")
		textfield.setFlag(for: "KI")
		XCTAssertEqual(textfield.selectedCountry?.code, "KI")
		textfield.setFlag(for: "KW")
		XCTAssertEqual(textfield.selectedCountry?.code, "KW")
		textfield.setFlag(for: "KG")
		XCTAssertEqual(textfield.selectedCountry?.code, "KG")
		textfield.setFlag(for: "LA")
		XCTAssertEqual(textfield.selectedCountry?.code, "LA")
		textfield.setFlag(for: "LV")
		XCTAssertEqual(textfield.selectedCountry?.code, "LV")
		textfield.setFlag(for: "LB")
		XCTAssertEqual(textfield.selectedCountry?.code, "LB")
		textfield.setFlag(for: "LS")
		XCTAssertEqual(textfield.selectedCountry?.code, "LS")
		textfield.setFlag(for: "LR")
		XCTAssertEqual(textfield.selectedCountry?.code, "LR")
		textfield.setFlag(for: "LY")
		XCTAssertEqual(textfield.selectedCountry?.code, "LY")
		textfield.setFlag(for: "LI")
		XCTAssertEqual(textfield.selectedCountry?.code, "LI")
		textfield.setFlag(for: "LT")
		XCTAssertEqual(textfield.selectedCountry?.code, "LT")
		textfield.setFlag(for: "LU")
		XCTAssertEqual(textfield.selectedCountry?.code, "LU")
		textfield.setFlag(for: "MO")
		XCTAssertEqual(textfield.selectedCountry?.code, "MO")
		textfield.setFlag(for: "MK")
		XCTAssertEqual(textfield.selectedCountry?.code, "MK")
		textfield.setFlag(for: "MG")
		XCTAssertEqual(textfield.selectedCountry?.code, "MG")
		textfield.setFlag(for: "MW")
		XCTAssertEqual(textfield.selectedCountry?.code, "MW")
		textfield.setFlag(for: "MY")
		XCTAssertEqual(textfield.selectedCountry?.code, "MY")
		textfield.setFlag(for: "MV")
		XCTAssertEqual(textfield.selectedCountry?.code, "MV")
		textfield.setFlag(for: "ML")
		XCTAssertEqual(textfield.selectedCountry?.code, "ML")
		textfield.setFlag(for: "MT")
		XCTAssertEqual(textfield.selectedCountry?.code, "MT")
		textfield.setFlag(for: "MH")
		XCTAssertEqual(textfield.selectedCountry?.code, "MH")
		textfield.setFlag(for: "MQ")
		XCTAssertEqual(textfield.selectedCountry?.code, "MQ")
		textfield.setFlag(for: "MR")
		XCTAssertEqual(textfield.selectedCountry?.code, "MR")
		textfield.setFlag(for: "MU")
		XCTAssertEqual(textfield.selectedCountry?.code, "MU")
		textfield.setFlag(for: "YT")
		XCTAssertEqual(textfield.selectedCountry?.code, "YT")
		textfield.setFlag(for: "MX")
		XCTAssertEqual(textfield.selectedCountry?.code, "MX")
		textfield.setFlag(for: "FM")
		XCTAssertEqual(textfield.selectedCountry?.code, "FM")
		textfield.setFlag(for: "MD")
		XCTAssertEqual(textfield.selectedCountry?.code, "MD")
		textfield.setFlag(for: "MC")
		XCTAssertEqual(textfield.selectedCountry?.code, "MC")
		textfield.setFlag(for: "MN")
		XCTAssertEqual(textfield.selectedCountry?.code, "MN")
		textfield.setFlag(for: "ME")
		XCTAssertEqual(textfield.selectedCountry?.code, "ME")
		textfield.setFlag(for: "MS")
		XCTAssertEqual(textfield.selectedCountry?.code, "MS")
		textfield.setFlag(for: "MA")
		XCTAssertEqual(textfield.selectedCountry?.code, "MA")
		textfield.setFlag(for: "MZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "MZ")
		textfield.setFlag(for: "MM")
		XCTAssertEqual(textfield.selectedCountry?.code, "MM")
		textfield.setFlag(for: "NA")
		XCTAssertEqual(textfield.selectedCountry?.code, "NA")
		textfield.setFlag(for: "NR")
		XCTAssertEqual(textfield.selectedCountry?.code, "NR")
		textfield.setFlag(for: "NP")
		XCTAssertEqual(textfield.selectedCountry?.code, "NP")
		textfield.setFlag(for: "NL")
		XCTAssertEqual(textfield.selectedCountry?.code, "NL")
		textfield.setFlag(for: "NC")
		XCTAssertEqual(textfield.selectedCountry?.code, "NC")
		textfield.setFlag(for: "NZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "NZ")
		textfield.setFlag(for: "NI")
		XCTAssertEqual(textfield.selectedCountry?.code, "NI")
		textfield.setFlag(for: "NE")
		XCTAssertEqual(textfield.selectedCountry?.code, "NE")
		textfield.setFlag(for: "NG")
		XCTAssertEqual(textfield.selectedCountry?.code, "NG")
		textfield.setFlag(for: "NU")
		XCTAssertEqual(textfield.selectedCountry?.code, "NU")
		textfield.setFlag(for: "NF")
		XCTAssertEqual(textfield.selectedCountry?.code, "NF")
		textfield.setFlag(for: "KP")
		XCTAssertEqual(textfield.selectedCountry?.code, "KP")
		textfield.setFlag(for: "MP")
		XCTAssertEqual(textfield.selectedCountry?.code, "MP")
		textfield.setFlag(for: "NO")
		XCTAssertEqual(textfield.selectedCountry?.code, "NO")
		textfield.setFlag(for: "OM")
		XCTAssertEqual(textfield.selectedCountry?.code, "OM")
		textfield.setFlag(for: "PK")
		XCTAssertEqual(textfield.selectedCountry?.code, "PK")
		textfield.setFlag(for: "PW")
		XCTAssertEqual(textfield.selectedCountry?.code, "PW")
		textfield.setFlag(for: "PS")
		XCTAssertEqual(textfield.selectedCountry?.code, "PS")
		textfield.setFlag(for: "PA")
		XCTAssertEqual(textfield.selectedCountry?.code, "PA")
		textfield.setFlag(for: "PG")
		XCTAssertEqual(textfield.selectedCountry?.code, "PG")
		textfield.setFlag(for: "PY")
		XCTAssertEqual(textfield.selectedCountry?.code, "PY")
		textfield.setFlag(for: "PE")
		XCTAssertEqual(textfield.selectedCountry?.code, "PE")
		textfield.setFlag(for: "PH")
		XCTAssertEqual(textfield.selectedCountry?.code, "PH")
		textfield.setFlag(for: "PL")
		XCTAssertEqual(textfield.selectedCountry?.code, "PL")
		textfield.setFlag(for: "PT")
		XCTAssertEqual(textfield.selectedCountry?.code, "PT")
		textfield.setFlag(for: "PR")
		XCTAssertEqual(textfield.selectedCountry?.code, "PR")
		textfield.setFlag(for: "QA")
		XCTAssertEqual(textfield.selectedCountry?.code, "QA")
		textfield.setFlag(for: "RE")
		XCTAssertEqual(textfield.selectedCountry?.code, "RE")
		textfield.setFlag(for: "RO")
		XCTAssertEqual(textfield.selectedCountry?.code, "RO")
		textfield.setFlag(for: "RU")
		XCTAssertEqual(textfield.selectedCountry?.code, "RU")
		textfield.setFlag(for: "RW")
		XCTAssertEqual(textfield.selectedCountry?.code, "RW")
		textfield.setFlag(for: "WS")
		XCTAssertEqual(textfield.selectedCountry?.code, "WS")
		textfield.setFlag(for: "SM")
		XCTAssertEqual(textfield.selectedCountry?.code, "SM")
		textfield.setFlag(for: "SA")
		XCTAssertEqual(textfield.selectedCountry?.code, "SA")
		textfield.setFlag(for: "ST")
		XCTAssertEqual(textfield.selectedCountry?.code, "ST")
		textfield.setFlag(for: "SN")
		XCTAssertEqual(textfield.selectedCountry?.code, "SN")
		textfield.setFlag(for: "RS")
		XCTAssertEqual(textfield.selectedCountry?.code, "RS")
		textfield.setFlag(for: "SC")
		XCTAssertEqual(textfield.selectedCountry?.code, "SC")
		textfield.setFlag(for: "SL")
		XCTAssertEqual(textfield.selectedCountry?.code, "SL")
		textfield.setFlag(for: "SG")
		XCTAssertEqual(textfield.selectedCountry?.code, "SG")
		textfield.setFlag(for: "SK")
		XCTAssertEqual(textfield.selectedCountry?.code, "SK")
		textfield.setFlag(for: "SI")
		XCTAssertEqual(textfield.selectedCountry?.code, "SI")
		textfield.setFlag(for: "SB")
		XCTAssertEqual(textfield.selectedCountry?.code, "SB")
		textfield.setFlag(for: "SO")
		XCTAssertEqual(textfield.selectedCountry?.code, "SO")
		textfield.setFlag(for: "ZA")
		XCTAssertEqual(textfield.selectedCountry?.code, "ZA")
		textfield.setFlag(for: "KR")
		XCTAssertEqual(textfield.selectedCountry?.code, "KR")
		textfield.setFlag(for: "SS")
		XCTAssertEqual(textfield.selectedCountry?.code, "SS")
		textfield.setFlag(for: "ES")
		XCTAssertEqual(textfield.selectedCountry?.code, "ES")
		textfield.setFlag(for: "LK")
		XCTAssertEqual(textfield.selectedCountry?.code, "LK")
		textfield.setFlag(for: "BL")
		XCTAssertEqual(textfield.selectedCountry?.code, "BL")
		textfield.setFlag(for: "SH")
		XCTAssertEqual(textfield.selectedCountry?.code, "SH")
		textfield.setFlag(for: "KN")
		XCTAssertEqual(textfield.selectedCountry?.code, "KN")
		textfield.setFlag(for: "LC")
		XCTAssertEqual(textfield.selectedCountry?.code, "LC")
		textfield.setFlag(for: "MF")
		XCTAssertEqual(textfield.selectedCountry?.code, "MF")
		textfield.setFlag(for: "PM")
		XCTAssertEqual(textfield.selectedCountry?.code, "PM")
		textfield.setFlag(for: "VC")
		XCTAssertEqual(textfield.selectedCountry?.code, "VC")
		textfield.setFlag(for: "SD")
		XCTAssertEqual(textfield.selectedCountry?.code, "SD")
		textfield.setFlag(for: "SR")
		XCTAssertEqual(textfield.selectedCountry?.code, "SR")
		textfield.setFlag(for: "SJ")
		XCTAssertEqual(textfield.selectedCountry?.code, "SJ")
		textfield.setFlag(for: "SZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "SZ")
		textfield.setFlag(for: "SE")
		XCTAssertEqual(textfield.selectedCountry?.code, "SE")
		textfield.setFlag(for: "CH")
		XCTAssertEqual(textfield.selectedCountry?.code, "CH")
		textfield.setFlag(for: "SY")
		XCTAssertEqual(textfield.selectedCountry?.code, "SY")
		textfield.setFlag(for: "TW")
		XCTAssertEqual(textfield.selectedCountry?.code, "TW")
		textfield.setFlag(for: "TJ")
		XCTAssertEqual(textfield.selectedCountry?.code, "TJ")
		textfield.setFlag(for: "TZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "TZ")
		textfield.setFlag(for: "TH")
		XCTAssertEqual(textfield.selectedCountry?.code, "TH")
		textfield.setFlag(for: "TL")
		XCTAssertEqual(textfield.selectedCountry?.code, "TL")
		textfield.setFlag(for: "TG")
		XCTAssertEqual(textfield.selectedCountry?.code, "TG")
		textfield.setFlag(for: "TK")
		XCTAssertEqual(textfield.selectedCountry?.code, "TK")
		textfield.setFlag(for: "TO")
		XCTAssertEqual(textfield.selectedCountry?.code, "TO")
		textfield.setFlag(for: "TT")
		XCTAssertEqual(textfield.selectedCountry?.code, "TT")
		textfield.setFlag(for: "TN")
		XCTAssertEqual(textfield.selectedCountry?.code, "TN")
		textfield.setFlag(for: "TR")
		XCTAssertEqual(textfield.selectedCountry?.code, "TR")
		textfield.setFlag(for: "TM")
		XCTAssertEqual(textfield.selectedCountry?.code, "TM")
		textfield.setFlag(for: "TC")
		XCTAssertEqual(textfield.selectedCountry?.code, "TC")
		textfield.setFlag(for: "TV")
		XCTAssertEqual(textfield.selectedCountry?.code, "TV")
		textfield.setFlag(for: "VI")
		XCTAssertEqual(textfield.selectedCountry?.code, "VI")
		textfield.setFlag(for: "UG")
		XCTAssertEqual(textfield.selectedCountry?.code, "UG")
		textfield.setFlag(for: "UA")
		XCTAssertEqual(textfield.selectedCountry?.code, "UA")
		textfield.setFlag(for: "AE")
		XCTAssertEqual(textfield.selectedCountry?.code, "AE")
		textfield.setFlag(for: "GB")
		XCTAssertEqual(textfield.selectedCountry?.code, "GB")
		textfield.setFlag(for: "US")
		XCTAssertEqual(textfield.selectedCountry?.code, "US")
		textfield.setFlag(for: "UY")
		XCTAssertEqual(textfield.selectedCountry?.code, "UY")
		textfield.setFlag(for: "UZ")
		XCTAssertEqual(textfield.selectedCountry?.code, "UZ")
		textfield.setFlag(for: "VU")
		XCTAssertEqual(textfield.selectedCountry?.code, "VU")
		textfield.setFlag(for: "VA")
		XCTAssertEqual(textfield.selectedCountry?.code, "VA")
		textfield.setFlag(for: "VE")
		XCTAssertEqual(textfield.selectedCountry?.code, "VE")
		textfield.setFlag(for: "VN")
		XCTAssertEqual(textfield.selectedCountry?.code, "VN")
		textfield.setFlag(for: "WF")
		XCTAssertEqual(textfield.selectedCountry?.code, "WF")
		textfield.setFlag(for: "YE")
		XCTAssertEqual(textfield.selectedCountry?.code, "YE")
		textfield.setFlag(for: "ZM")
		XCTAssertEqual(textfield.selectedCountry?.code, "ZM")
		textfield.setFlag(for: "ZW")
		XCTAssertEqual(textfield.selectedCountry?.code, "ZW")
	}
}
